### ISSUE TITLE
Checkpointing seems to fail after other worker has taken lease

### ISSUE THREAD

**Issue by scho** [awslabs/amazon-kinesis-client#108]
Hi,

from time to time (every couple of days) we encounter the following situation (I've shortened all shard ids/sequence numbers to improve readability):

- `worker-a` processes `shard-01` and `shardId-02`.
- `worker-b` is started and takes lease for `shardId-02`.
- `worker-a` tries to checkpoint sequence number `00001` of `shardId-02`, but fails with the following reason:
```
com.amazonaws.services.kinesis.leases.impl.LeaseRenewer: Worker worker-a lost lease with key shardId-02 - discovered during update
```
- `worker-b` says:
```
com.amazonaws.services.kinesis.leases.impl.LeaseTaker: Worker worker-b successfully took 1 leases: shardId-02
com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher: Initializing shard shardId-02 with 00001
```

The way I see it is, that `worker-a` seems to fail to checkpoint, but is successful instead.
The fact, that `worker-b` then initializes itself with the same sequence number, tells me, that checkpointing succeeded anyways. Otherwise, `worker-b` would not know anything about that particular sequence number.

Could this be a bug in the KPL?

We are using version `1.6.3` of the KPL.

**Comment by pfifer** [comment]
It sounds like it did succeed it's last checkpoint.  The error message you would see when the checkpoint fails due to lease loss is [Can't update checkpoint - instance doesn't hold the lease for this shard](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibLeaseCoordinator.java#L172)

The message you're seeing is likely related to the lease renewer finding that the record processor doesn't hold the lease anymore.  At that point in time the record processor will be terminated with the shutdown reason of ZOMBIE.

**Comment by scho** [comment]
Sorry, I forgot to mention, that we get an exception on checkpointing as well. 

What we see on when `worker-a` is trying to checkpoint is:

The Log message (INFO) 2ms prior checkpointing:
```
com.amazonaws.services.kinesis.leases.impl.LeaseRenewer: Worker worker-a lost lease with key shardId-02 - discovered during update
```
The following exception when calling `IRecordProcessorCheckpointer::checkpoint(record)`:
```
com.amazonaws.services.kinesis.clientlibrary.exceptions.ShutdownException: Can't update checkpoint - instance doesn't hold the lease for this shard
```

**Comment by pfifer** [comment]
In your log configuration could you enable debug for [com.amazonaws.services.kinesis.leases.impl.LeaseManager](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/leases/impl/LeaseManager.java).  There are some additional logging messages there that should indicate state, and outcome of the checkpoint request.

Specifically looking to see the outcome of [LeaseManager#updateLease](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/leases/impl/LeaseManager.java#L539).

Thanks

**Comment by scho** [comment]
We've switched on debug for the LeaseManager as you have requested. This is the outcome:

```
DEBUG [2016-10-24 16:37:51,874] [7943c6c0a6617715] com.amazonaws.services.kinesis.leases.impl.LeaseManager: Updating lease {"checkpoint":{"subSequenceNumber":0,"sequenceNumber":"49566801942532034758569254971987374089724020857906397218"},"lastCounterIncrementNanos":20582979558973,"leaseCounter":846494,"ownerSwitchesSinceCheckpoint":0,"leaseKey":"shardId-000000000002","parentShardIds":[],"leaseOwner":"10.61.205.222","concurrencyToken":"825d226d-c1ed-4ffb-99d9-2807b164be0d"}
DEBUG [2016-10-24 16:38:03,124] [39cd72f2dea6953f] com.amazonaws.services.kinesis.leases.impl.LeaseManager: Renewing lease with key shardId-000000000002
DEBUG [2016-10-24 16:38:03,124] [7943c6c0a6617715] com.amazonaws.services.kinesis.leases.impl.LeaseManager: Lease update failed for lease with key shardId-000000000002 because the lease counter was not 846494
INFO [2016-10-24 16:38:03,124] [7943c6c0a6617715] com.amazonaws.services.kinesis.leases.impl.LeaseRenewer: Worker 10.61.205.222 lost lease with key shardId-000000000002 - discovered during update
```

Now, checkpointing fails with the following exception:
```
WARN [2016-10-24 16:38:03,127] [7943c6c0a6617715]  com.amazonaws.services.kinesis.clientlibrary.exceptions.ShutdownException: Can't update checkpoint - instance doesn't hold the lease for this shard
```

Then we see the following logs:
```
DEBUG [2016-10-24 16:38:03,129] [39cd72f2dea6953f] com.amazonaws.services.kinesis.leases.impl.LeaseManager: Lease renewal failed for lease with key shardId-000000000002 because the lease counter was not 846494
INFO [2016-10-24 16:38:03,129] [39cd72f2dea6953f] com.amazonaws.services.kinesis.leases.impl.LeaseRenewer: Worker 10.61.205.222 lost lease with key shardId-000000000002
```

Now, we shut down the worker/record processor and start it again. Then we see the following message:
```
INFO [2016-10-24 16:39:25,180] [39cd72f2dea6953f] com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher: Initializing shard shardId-000000000002 with 49566801942532034758569254971987374089724020857906397218
```

**Comment by BenRomberg** [comment]
@pfifer any ideas what else we could do? Any insights would be greatly appreciated!

**Comment by pfifer** [comment]
What is the value for [failoverTimeMillis](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfiguration.java#L332)?  Is it possible the lease renewer thread isn't getting a chance to run?  Enabling debug logging for the [LeaseRenewer](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/leases/impl/LeaseRenewer.java#L184) may help to determine that.

**Comment by scho** [comment]
The `failoverTimeMillis` is set to `30_000` (30 sec).
What we currently think is happening is similiar to https://github.com/awslabs/amazon-kinesis-connectors/issues/10.
The RecordProcessor looses the lease for a moment but then gets it back and just continues processing.

**Comment by pfifer** [comment]
I've been looking through the code, and I have a suspicion that there may be a race condition.  There might be an update race between the lease renewer, and the checkpoint process if they overlap in just the right way.  

I'll need to do some more investigation before I can say for sure.

**Comment by pmatpadi** [comment]
We experienced similar issue with cpu maxed out on t2.medium instance. We setup our cluster to c4.xlarge, which helped resolving this issue.

**Comment by pfifer** [comment]
I'm still not completely sure, but there is a possibility that the call to DynamoDB is thought to have failed, but actually succeeded making it look like the lease was lost.  I'm working on adding logging or other detection to it: https://github.com/pfifer/amazon-kinesis-client/commit/579711245f5295bd1b3ef44cd1e70b6adfff2f9b

I don't have a really testable version for it yet, but I'll be trying to do that sometime soon.

**Comment by andrewmilkowski** [comment]
this defect leads to spark with kinesis connector not being freed up, we id' exact block id to this exception, full stack trace below, also filled jira with spark on the topic: https://issues.apache.org/jira/browse/SPARK-19364

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/mnt/yarn/usercache/hadoop/filecache/24/__spark_libs__7928020266533182031.zip/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
17/01/26 13:52:00 ERROR KinesisRecordProcessor: ShutdownException:  Caught shutdown exception, skipping checkpoint.
com.amazonaws.services.kinesis.clientlibrary.exceptions.ShutdownException: Can't update checkpoint - instance doesn't hold the lease for this shard
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.setCheckpoint(KinesisClientLibLeaseCoordinator.java:120)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.RecordProcessorCheckpointer.advancePosition(RecordProcessorCheckpointer.java:216)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.RecordProcessorCheckpointer.checkpoint(RecordProcessorCheckpointer.java:137)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.RecordProcessorCheckpointer.checkpoint(RecordProcessorCheckpointer.java:103)
	at org.apache.spark.streaming.kinesis.KinesisCheckpointer$$anonfun$checkpoint$1$$anonfun$apply$1.apply$mcV$sp(KinesisCheckpointer.scala:81)
	at org.apache.spark.streaming.kinesis.KinesisCheckpointer$$anonfun$checkpoint$1$$anonfun$apply$1.apply(KinesisCheckpointer.scala:81)
	at org.apache.spark.streaming.kinesis.KinesisCheckpointer$$anonfun$checkpoint$1$$anonfun$apply$1.apply(KinesisCheckpointer.scala:81)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.streaming.kinesis.KinesisRecordProcessor$.retryRandom(KinesisRecordProcessor.scala:144)
	at org.apache.spark.streaming.kinesis.KinesisCheckpointer$$anonfun$checkpoint$1.apply(KinesisCheckpointer.scala:81)
	at org.apache.spark.streaming.kinesis.KinesisCheckpointer$$anonfun$checkpoint$1.apply(KinesisCheckpointer.scala:75)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.streaming.kinesis.KinesisCheckpointer.checkpoint(KinesisCheckpointer.scala:75)
	at org.apache.spark.streaming.kinesis.KinesisCheckpointer.org$apache$spark$streaming$kinesis$KinesisCheckpointer$$checkpointAll(KinesisCheckpointer.scala:103)
	at org.apache.spark.streaming.kinesis.KinesisCheckpointer$$anonfun$1.apply$mcVJ$sp(KinesisCheckpointer.scala:117)
	at org.apache.spark.streaming.util.RecurringTimer.triggerActionForNextInterval(RecurringTimer.scala:94)
	at org.apache.spark.streaming.util.RecurringTimer.org$apache$spark$streaming$util$RecurringTimer$$loop(RecurringTimer.scala:106)
	at org.apache.spark.streaming.util.RecurringTimer$$anon$1.run(RecurringTimer.scala:29)

**Comment by pfifer** [comment]
@andrewmilkowski I just want to make sure: Are you seeing the checkpoint actually write the value to DynamoDB, but then return a failure?

It's possible, and normal, that a checkpoint will fail if the lease is stolen for any reason.

**Comment by andrewmilkowski** [comment]
every time I receive that exception stream block fails to remove from memory and piles up, with 100% consistency , that is I co-relate node IP in the cluster with a stream block node ip not being freed up, every single time

**Comment by chappidmAWS** [comment]
Here is the workflow I observed during job restart (Spark perspective) with no DDB failures on checkpointing
For each Dstream, a kinesis receiver is created along with the KCL worker which picks the lease.
1. It is possible for a receiver to trigger/take all the leases during initiation.
--
Executor1:
17/03/08 18:08:35 INFO LeaseTaker: Worker ip-172-31-23-6.us-west-2.compute.internal:a74c5e82-beb8-44aa-8e6a-a9e581383fdb successfully took 5 leases: shardId-000000000004, shardId-000000000003, shardId-000000000002, shardId-000000000001, shardId-000000000000
--
2. Then another receiver in different executor can takeover the lease as executor1 is full and to maintain uniformity.
--
17/03/08 18:08:36 INFO LeaseTaker: Worker ip-172-31-22-13.us-west-2.compute.internal:b4c3ce91-ede2-412d-96ab-3f095d2a5374 needed 2 leases but none were expired, so it will steal lease shardId-000000000003 from ip-172-31-23-6.us-west-2.compute.internal:a74c5e82-beb8-44aa-8e6a-a9e581383fdb
17/03/08 18:08:36 INFO LeaseTaker: Worker ip-172-31-22-13.us-west-2.compute.internal:b4c3ce91-ede2-412d-96ab-3f095d2a5374 saw 5 total leases, 0 available leases, 4 workers. Target is 2 leases, I have 0 leases, I will take 1 leases
17/03/08 18:08:36 INFO LeaseTaker: Worker ip-172-31-22-13.us-west-2.compute.internal:b4c3ce91-ede2-412d-96ab-3f095d2a5374 successfully took 1 leases: shardId-000000000003
--

Implies,
T0 -> executor1 picks the records, creates the blocks and send it to BlockGenerator(RDD) before checkpoint
T1 -> executor4 comes and takes over the lease, creates the blocks and send it to BlockGenerator(RDD) before checkpoint
T2 -> executor1 tries to checkpoint but fails as it doesn't have lease.
--
17/03/08 18:08:38 INFO KinesisClientLibLeaseCoordinator: Worker ip-172-31-23-6.us-west-2.compute.internal:a74c5e82-beb8-44aa-8e6a-a9e581383fdb could not update checkpoint for shard shardId-000000000003 because it does not hold the lease
17/03/08 18:08:38 ERROR KinesisRecordProcessor: ShutdownException:  Caught shutdown exception, skipping checkpoint.
com.amazonaws.services.kinesis.clientlibrary.exceptions.ShutdownException: Can't update checkpoint - instance doesn't hold the lease for this shard
--
T3 -> executor4 checkpoints and proceeds further.

**Comment by gregakespret** [comment]
@pfifer We're getting the same error when running KCL inside Spark Streaming Kinesis integration. I've added some more info [here](https://stackoverflow.com/questions/47644984/spark-streaming-using-kinesis-doesnt-work-if-shard-checkpoints-exist-in-dynamod) and filed also [SPARK-22685](https://issues.apache.org/jira/browse/SPARK-22685), but this looks to be KCL issue.

In our case, it looks like this happens when starting the app, using existing checkpoints in DynamoDB. It could be that this just speeds up the appearance of this issue, I haven't done a lot of debugging yet.

Do you have any suggestion as to what I can try or what I should look at?

Thanks

**Comment by ryonday** [comment]
I'm seeing this using the DynamoDB Streams Kinesis adapter.

**Comment by casidiablo** [comment]
By the way, I noticed that this could also happen if the checkpointing table is underprovisioned for writes. In that case, the workers will start failing to checkpoint (because they get throttled), and other workers will start stealing the lease.

**Comment by klesniewski** [comment]
I'm seeing this using the DynamoDB Streams Kinesis adapter with KCL 1.9.2. The KCL state table capacity seems fine and I didn't notice any throttling. @pfifer any chances on resolving this? By looking at logs, we encounter it once, maybe twice daily.

**Comment by dharmeshspatel4u** [comment]
@pfifer  with client v1.8.1 having below issue. I found this issue close to my issue.

```

2019-02-09 21:10:01.875  INFO 26971 --- [      Thread-29] c.a.s.k.clientlibrary.lib.worker.Worker  : Worker shutdown requested.
2019-02-09 21:10:01.876  INFO 26971 --- [      Thread-29] c.a.s.k.leases.impl.LeaseCoordinator     : Worker ip-1234. has successfully stopped lease-tracking threads
2019-02-09 21:10:01.877  INFO 26971 --- [dProcessor-0000] c.c.d.v.s.p.KinesisRecordProcessor       : Checkpointing shard shardId-000000000000
2019-02-09 21:10:01.878  INFO 26971 --- [dProcessor-0000] k.c.l.w.KinesisClientLibLeaseCoordinator : Worker ip-1234. could not update checkpoint for shard shardId-000000000000 because it does not hold the lease
2019-02-09 21:10:01.878  INFO 26971 --- [dProcessor-0000] c.c.d.v.s.p.KinesisRecordProcessor       : Caught shutdown exception, skipping checkpoint.

com.amazonaws.services.kinesis.clientlibrary.exceptions.ShutdownException: Can't update checkpoint - instance doesn't hold the lease for this shard
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.setCheckpoint(KinesisClientLibLeaseCoordinator.java:174) ~[amazon-kinesis-client-1.8.1.jar!/:na]
```

Any clue, if this is my issue? I see sometimes checkpoint gets updated, sometimes throws above error and it delivers again those messages back to consumer. Is this fixed in 2.0.4? I have very major upgrade to do so looking to seeif 1.x has fix for above issue.

appreciate your quick response.

**Comment by cmcnelis** [comment]
Running into same symptoms. Just started happening out of the blue a couple of days ago . KCL 1.9.2  DynamoDBStream version 1.4.0. Seeing repeated leases stolen from workers also workers attempting 
```
02/22/201910:47:14.880 -0600 | INFO [2019-02-22 16:47:14,880] [RecordProcessor-1502] c.a.s.k.c.l.w.KinesisDataFetcher: Initializing shard shardId-00000001550840986131-382ec8f8 with 24438822900000000000168706143
-- | --
4 | 02/22/201910:47:14.375 -0600 | INFO [2019-02-22 16:47:14,375] [RecordProcessor-1528] c.a.s.k.c.l.w.BlockOnParentShardTask: No need to block on parents [shardId-00000001550826396972-b6ad67ea] of shard shardId-00000001550840986131-382ec8f8
5 | 02/22/201910:47:14.372 -0600 | INFO [2019-02-22 16:47:14,372] [pool-27-thread-1] c.a.s.k.c.lib.worker.Worker: Created new shardConsumer for : ShardInfo [shardId=shardId-00000001550840986131-382ec8f8, concurrencyToken=a268732c-a8c3-42b3-b1a1-3bd12f4351d3, parentShardIds=[shardId-00000001550826396972-b6ad67ea], checkpoint={SequenceNumber: 24438822900000000000168706143,SubsequenceNumber: 0}]
6 | 02/22/201910:47:14.246 -0600 | INFO [2019-02-22 16:47:14,246] [LeaseCoordinator-0005] c.a.s.k.leases.impl.LeaseTaker: Worker c01cb719-dc24-4a64-b3d4-5fa1e07e3019 successfully took 114 leases: shardId-00000001550830283919-0c9bf4ed, shardId-00000001550817654201-47fc24cb, shardId-00000001550822191016-16e37344, shardId-00000001550836730356-fa15e581, shardId-00000001550828688808-146ade81, shardId-00000001550835609053-b4c3bc87, shardId-00000001550812711343-4e9619e5, shardId-00000001550824477552-e55d135b, shardId-00000001550808470271-66644e1e, shardId-00000001550841040479-7b2c36ee, shardId-00000001550809202588-5cf2e8ae, shardId-00000001550824737128-c65313f1, shardId-00000001550820347214-7b1cfa66, shardId-00000001550839834100-fe916161, shardId-00000001550820120059-ca2c7b0c, shardId-00000001550813319404-65b22c89, shardId-00000001550822121034-90493c8b, shardId-00000001550836575149-ab1fa0e6, shardId-00000001550826418936-0163f61f, shardId-00000001550825498028-020faaa1, shardId-00000001550803775433-d40fa612, shardId-00000001550809041692-68f17819, shardId-00000001550822332848-a8424ce3, shardId-00000001550823608588-240aaad1, shardId-00000001550826848401-9890153d, shardId-00000001550837673016-0608aad8, shardId-00000001550827246240-8c2c4bee, shardId-00000001550841414721-b933bff9, shardId-00000001550812914512-c3a552c0, shardId-00000001550814987843-4436d2e0, shardId-00000001550838178023-14605f0b, shardId-00000001550838128729-2d1dff9f, shardId-00000001550835584617-8d33eeb7, shardId-00000001550835760714-94e52020, shardId-00000001550814470562-6ae5ff42, shardId-00000001550832009379-d5e7d401, shardId-00000001550840452441-535296e6, shardId-00000001550834269958-90e59b68, shardId-00000001550837873902-1d2f8321, shardId-00000001550812531834-14f3d095, shardId-00000001550840313809-81a2bd17, shardId-00000001550827444220-73441d70, shardId-00000001550815135479-47e5ae44, shardId-00000001550837267295-2b879a4f, shardId-00000001550831362064-eaeb99a9, shardId-00000001550818757839-54db0645, shardId-00000001550840149670-93eef590, shardId-00000001550813246208-93f2ce32, shardId-00000001550822533530-c499ec33, shardId-00000001550812125454-ddbdea38, shardId-00000001550806831479-64c57908, shardId-00000001550823542591-be186d1c, shardId-00000001550822866731-8a7052a1, shardId-00000001550824561689-78c888d4, shardId-00000001550803153429-1d2c8b31, shardId-00000001550826396972-b6ad67ea, shardId-00000001550814641897-e2001eee, shardId-00000001550828064059-0d88b50a, shardId-00000001550817114036-4ebc06b9, shardId-00000001550816994183-eaebeabf, shardId-00000001550848559220-c3692334, shardId-00000001550823446164-95d215f7, shardId-00000001550831553159-b54b201d, shardId-00000001550840107105-3252c564, shardId-00000001550818518258-9b2ef5d2, shardId-00000001550808131366-9e700623, shardId-00000001550816284620-073530fa, shardId-00000001550813500862-772ac160, shardId-00000001550827515389-6f4c9acd, shardId-00000001550806882094-940c102e, shardId-00000001550832882501-515eccba, shardId-00000001550841397222-0d36c88c, shardId-00000001550820062455-a2f5cb0d, shardId-00000001550817701435-bf787261, shardId-00000001550836220309-2b8f6596, shardId-00000001550827451717-063fa12b, shardId-00000001550816271408-c29e9903, shardId-00000001550848249455-41be746b, shardId-00000001550804969809-485ba778, shardId-00000001550821752978-087467b1, shardId-00000001550842017768-3fc34090, shardId-00000001550823236914-5cbaaacf, shardId-00000001550806192725-0010462a, shardId-00000001550821604375-9787a392, shardId-00000001550840986131-382ec8f8, shardId-00000001550838722658-116fdbc1, shardId-00000001550848535251-ad31ae97, shardId-00000001550817492166-82d8640c, shardId-00000001550824991363-b69a5cfc, shardId-00000001550839513016-23948640, shardId-00000001550841104994-56b4a836, shardId-00000001550828989396-79db3c68, shardId-00000001550838834783-975bb15f, shardId-00000001550826397428-d870f91c, shardId-00000001550819017020-de2deb3f, shardId-00000001550813472112-e6196737, shardId-00000001550832619597-bd8f57a3, shardId-00000001550804328812-e47dcde3, shardId-00000001550837088203-13f37cf3, shardId-00000001550837212442-1ac5b3e6, shardId-00000001550824328925-76933764, shardId-00000001550831864587-16df1f65, shardId-00000001550816406501-5ce546d4, shardId-00000001550844075217-d2502a35, shardId-00000001550833111966-98e4a5b0, shardId-00000001550836255185-3d1d05df, shardId-00000001550821650318-b2c038ff, shardId-00000001550811352748-d24aa5bd, shardId-00000001550806641022-013198b5, shardId-00000001550826396637-1cf510b2, shardId-00000001550817959096-737c3307, shardId-00000001550808878616-ab33d6b3, shardId-00000001550837903263-6a00f34d, shardId-00000001550817840929-6784886b...
7 | 02/22/201910:46:40.902 -0600 | INFO [2019-02-22 16:46:40,902] [RecordProcessor-1504] c.a.s.k.c.l.w.KinesisClientLibLeaseCoordinator: Worker c01cb719-dc24-4a64-b3d4-5fa1e07e3019 could not update checkpoint for shard shardId-00000001550840986131-382ec8f8 because it does not hold the lease 
8 | 02/22/201910:46:35.901 -0600 | INFO [2019-02-22 16:46:35,901] [RecordProcessor-1504] c.a.s.k.c.l.w.KinesisClientLibLeaseCoordinator: Worker c01cb719-dc24-4a64-b3d4-5fa1e07e3019 could not update checkpoint for shard shardId-00000001550840986131-382ec8f8 because it does not hold the lease
9 | 02/22/201910:46:30.901 -0600 | INFO [2019-02-22 16:46:30,901] [RecordProcessor-1504] c.a.s.k.c.l.w.KinesisClientLibLeaseCoordinator: Worker c01cb719-dc24-4a64-b3d4-5fa1e07e3019 could not update checkpoint for shard shardId-00000001550840986131-382ec8f8 because it does not hold the lease
10 | 02/22/201910:46:14.176 -0600 | INFO [2019-02-22 16:46:14,176] [LeaseRenewer-0038] c.a.s.k.leases.impl.LeaseRenewer: Worker c01cb719-dc24-4a64-b3d4-5fa1e07e3019 lost lease with key shardId-00000001550840986131-382ec8f8
11 | 02/22/201910:45:44.168 -0600 | INFO [2019-02-22 16:45:44,168] [pool-27-thread-1] c.a.s.k.c.lib.worker.Worker: Current stream shard assignments: shardId-00000001550852034677-ec7ec441, shardId-00000001550852886204-07ff80e0, shardId-00000001550848884237-2c8fcb28, shardId-00000001550852735424-55c0262d, shardId-00000001550840318028-cf10d650, shardId-00000001550852570359-a57483a7, shardId-00000001550853726389-42d69bce, shardId-00000001550848559220-c3692334, shardId-00000001550840107105-3252c564, shardId-00000001550840301820-624e8703, shardId-00000001550841801787-a2404e43, shardId-00000001550841040479-7b2c36ee, shardId-00000001550851896664-784ff458, shardId-00000001550841397222-0d36c88c, shardId-00000001550853729619-4a721ebd, shardId-00000001550841102123-ef19d28c, shardId-00000001550850822019-86f20751, shardId-00000001550848249455-41be746b, shardId-00000001550851195485-9173c19e, shardId-00000001550850755942-13cfb61c, shardId-00000001550851814414-08090181, shardId-00000001550845474451-fc87c4ec, shardId-00000001550850967628-2fb6e379, shardId-00000001550838447667-d681e56d, shardId-00000001550852915984-25ea93e8, shardId-00000001550852471046-78e05dc4, shardId-00000001550842017768-3fc34090, shardId-00000001550850364214-0246f0e4, shardId-00000001550840986131-382ec8f8, shardId-00000001550841414721-b933bff9, shardId-00000001550848535251-ad31ae97, shardId-00000001550850887547-7b33ec7b, shardId-00000001550852600474-3fb67486, shardId-00000001550838834783-975bb15f, shardId-00000001550849239039-7f1ef0a2, shardId-00000001550841925498-5063238e, shardId-00000001550850561808-fce2ee84, shardId-00000001550853719170-31644010, shardId-00000001550844075217-d2502a35, shardId-00000001550850039610-6784f74a, shardId-00000001550850402607-9f4534fd, shardId-00000001550848701715-7ea2bbf7, shardId-00000001550852304953-64244ca5, shardId-00000001550842044979-53f29d12, shardId-00000001550840313809-81a2bd17, shardId-00000001550852192795-a0215ead, shardId-00000001550840149670-93eef590, shardId-00000001550850853556-eb5ece93, shardId-00000001550850037138-96022e9e...
12 | 02/22/201910:44:40.619 -0600 | INFO [2019-02-22 16:44:40,619] [pool-27-thread-1] c.a.s.k.c.lib.worker.Worker: Current stream shard assignments: shardId-00000001550852034677-ec7ec441, shardId-00000001550852886204-07ff80e0, shardId-00000001550848884237-2c8fcb28, shardId-00000001550852735424-55c0262d, shardId-00000001550840318028-cf10d650, shardId-00000001550852570359-a57483a7, shardId-00000001550853726389-42d69bce, shardId-00000001550848559220-c3692334, shardId-00000001550840107105-3252c564, shardId-00000001550840301820-624e8703, shardId-00000001550841801787-a2404e43, shardId-00000001550841040479-7b2c36ee, shardId-00000001550851896664-784ff458, shardId-00000001550841397222-0d36c88c, shardId-00000001550853729619-4a721ebd, shardId-00000001550841102123-ef19d28c, shardId-00000001550850822019-86f20751, shardId-00000001550848249455-41be746b, shardId-00000001550851195485-9173c19e, shardId-00000001550850755942-13cfb61c, shardId-00000001550851814414-08090181, shardId-00000001550845474451-fc87c4ec, shardId-00000001550850967628-2fb6e379, shardId-00000001550838447667-d681e56d, shardId-00000001550852915984-25ea93e8, shardId-00000001550852471046-78e05dc4, shardId-00000001550842017768-3fc34090, shardId-00000001550850364214-0246f0e4, shardId-00000001550840986131-382ec8f8, shardId-00000001550841414721-b933bff9, shardId-00000001550848535251-ad31ae97, shardId-00000001550850887547-7b33ec7b, shardId-00000001550852600474-3fb67486, shardId-00000001550838834783-975bb15f, shardId-00000001550849239039-7f1ef0a2, shardId-00000001550841925498-5063238e, shardId-00000001550850561808-fce2ee84, shardId-00000001550853719170-31644010, shardId-00000001550844075217-d2502a35, shardId-00000001550850039610-6784f74a, shardId-00000001550850402607-9f4534fd, shardId-00000001550848701715-7ea2bbf7, shardId-00000001550852304953-64244ca5, shardId-00000001550842044979-53f29d12, shardId-00000001550840313809-81a2bd17, shardId-00000001550852192795-a0215ead, shardId-00000001550840149670-93eef590, shardId-00000001550850853556-eb5ece93, shardId-00000001550850037138-96022e9e.. 02/22/201910:44:02.770 -0600

```
I am contemplating looking into the StreamsWorkerFactory.createDynamoDbStreamsWorker mentioned in other issues that have appeared to be similar.

@pfifer any guidance and or suggestions would be appreciated. I'm going to add some metrics around my worker but we haven't seen any downstream effects with respect to SLA for our clients but just seems pretty smelly jumping out of nowhere like this.

**Comment by adrian-baker** [comment]
Is this likely to have been fixed in the 2.x version?

**Comment by kheraankit** [comment]
Keeping it alive,  Running into similar issues lately
'amazon-kinesis-client', version: '2.2.7'
```
2020-06-17 20:50:59 INFO  s.a.k.l.d.DynamoDBLeaseRenewer:317 - 7011360996539966560 7710753708534499685 - Worker 1d830f82-9319-4125-b286-72dad83d120d lost lease with key shardId-000000000071 - discovered during update                                      │
│ 2020-06-17 20:50:59 ERROR c.l.l.s.RecordProcessor:168 - 7011360996539966560 2247803056832779720 - Caught throwable while processing records. Aborting: Can't update checkpoint - instance doesn't hold the lease for this shard                               │
│
```

**Comment by kheraankit** [comment]
Any updates?  Are there any more details that I can help provide.

**Comment by kheraankit** [comment]
@pfifer Currently, in our case, every consumer instance/pod processes approximately more than one shard e.g 3.  When we encounter this error `instance doesn't hold the lease for this shard` the current behavior is to catch the error and do a `System.exit(1)`.  This causes the consumer instance/pod to restart which in turn has a side effect of causing lags/interruptions on other shards which this consumer instance/pod was processing [i.e. other RecordProcessor objects].  Is that the right behavior or should we just ignore the exception as some other consumer instance/pod has already started processing this shard?
