### ISSUE TITLE
java.util.concurrent.TimeoutException when terminating multilang daemon process using CTRL+C

### ISSUE THREAD

**Issue by hsingh124** [awslabs/amazon-kinesis-client#1374]
Hi, I'm working with the Kinesis Multilang Daemon in PHP. Whenever I terminate the process using CTRL+C, I get the below logs:

```
2024-08-12 18:30:26,085 [multi-lang-daemon-0001] INFO  s.a.kinesis.multilang.LineReaderTask [NONE] - Stopping: Reading STDERR for shardId-000000000000 
2024-08-12 18:30:26,112 [Thread-1] ERROR s.a.k.multilang.MultiLangDaemon [NONE] - Encountered an error during shutdown. 
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1892)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2027)
	at software.amazon.kinesis.multilang.MultiLangDaemon.lambda$setupShutdownHook$0(MultiLangDaemon.java:183)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I'm not sure if the `java.util.concurrent.TimeoutException` is expected behaviour. If it is not, could I get some help on how to resolve this?

Thanks!

KCL Version: 2.5.8
Running this in a Ubuntu 20.04.6 LTS docker container.

**Comment by kevioke** [comment]
I ran into a similar problem, but I'm not sure if yours is exactly the same since I'm using the Go KCL. The way I solved it was by setting the following two settings in the properties file.

```
cleanupLeasesUponShardCompletion = true
shutdownGraceMillis = 10000
```

`shutdownGraceMillis` controls how long the multilang daemon will wait for the worker to respond to the shutdownRequested message. Without setting that, I was seeing an immediate timeout from the daemon. `cleanupLeasesUponShardCompletion` was needed because of some other issue I noticed. Hopefully this helps with your PHP KCL.

**Comment by hsingh124** [comment]
Hi @kevioke,

Thanks for the fix, it really helped! Using `kill -15` now shuts down the process gracefully. However, when I use CTRL+C, it starts to shut down but it seems the STDIN communication closes, so it can't receive status messages or send the `shutdownRequested` or `leaseLost` actions. I assume this is expected, and that KCL requires a SIGTERM signal for a graceful shutdown.

Thanks again for the help!
