### ISSUE TITLE
URISyntaxException: Expected authority at index 8: https://

### ISSUE THREAD

**Issue by ankon** [awslabs/amazon-kinesis-client#189]
~~~~
Exception in thread "main" java.lang.IllegalArgumentException: java.net.URISyntaxException: Expected authority at index 8: https://
	at com.amazonaws.util.RuntimeHttpUtils.toUri(RuntimeHttpUtils.java:156)
	at com.amazonaws.AmazonWebServiceClient.toURI(AmazonWebServiceClient.java:195)
	at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:185)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker$Builder.build(Worker.java:1053)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.buildWorker(MultiLangDaemon.java:81)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.<init>(MultiLangDaemon.java:75)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:145)
Caused by: java.net.URISyntaxException: Expected authority at index 8: https://
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.failExpecting(URI.java:2854)
	at java.net.URI$Parser.parseHierarchical(URI.java:3102)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at com.amazonaws.util.RuntimeHttpUtils.toUri(RuntimeHttpUtils.java:154)
	... 6 more
~~~~

I'm creating the properties dynamically, and this happens when setting the `kinesisEndpoint` property to an empty value. It would be nice if this could be handled gracefully (ignore/warn about empty values), or get caught earlier.

**Comment by pfifer** [comment]
Thanks for reporting this, but I would recommend simply omitting the value if it's empty.  

It seems like it could be a bug if the value was empty, but the user intended to provide a value.  As such this is an error that should trigger termination, since an invalid value would prevent the KCL from being able to communicate with Kinesis.  Allowing the KCL to proceed with an invalid value could cause odd behavior, and application to not work correctly.

**Comment by ankon** [comment]
Maybe I wasn't clear: I think the _bug_ part here is that the code actually goes so far as adding a 'https://' to the empty value, and then proceeds to try to parse that. Yes, I can (and by now do) check to not provide an empty value in my code, but for debugging purposes it seems the KCL part should check the value, and abort _earlier_, with a sensible message ("Empty endpoint is not allowed" or such).
