### ISSUE TITLE
Update jackson version to fix "jackson incompatible library version"

### ISSUE THREAD

**Issue by fan-n-akiyama** [awslabs/amazon-kinesis-client#200]
Got the following error when jackson-core was updated (to 2.8.9) by other library dependency:

```
2017-08-07 12:53:03,929 [ERROR] (com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask) Caught exception while sync'ing Kinesis s
hards and leases
com.amazonaws.SdkClientException: Unable to marshall request to JSON: Jackson jackson-core/jackson-dataformat-cbor incompatible library version d
etected.
You have two possible resolutions:
                1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
                2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance)
        at com.amazonaws.services.kinesis.model.transform.DescribeStreamRequestProtocolMarshaller.marshall(DescribeStreamRequestProtocolMarshaller.java:58)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:711)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:696)
        at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getStreamInfo(KinesisProxy.java:181)
        at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getShardList(KinesisProxy.java:243)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.getShardList(ShardSyncer.java:288)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:112)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:88)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask.call(ShardSyncTask.java:68)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:427)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:356)
```

The Jackson version seems too old. Could you update it to 2.8.x or higher?
Not sure if it will fix my issue though. I couldn't build this library locally even without any changes 😞

**Comment by pfifer** [comment]
The Jackson version is provided by the [AWS Java SDK](https://github.com/aws/aws-sdk-java/).  A new version of the [CBOR dependency exists](http://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor) if you want to force an upgrade of the Jackson library.

Feel free to reopen if you have additional questions.

**Comment by fan-n-akiyama** [comment]
Thanks. Adding `jackson-dataformat-cbor` dependency seem to fix it
