### ISSUE TITLE
incorrect describe stream request body

### ISSUE THREAD

**Issue by Everley1993** [awslabs/amazon-kinesis-client#272]
I run a localstack kinesis and MultiLangDaemon(builded from lastest src) for test.

I use tcpflow to capture the request from MultiLangDaemon to localstack kinesis

my stream name is `test`

```shell
127.000.000.001.37792-127.000.000.001.09001: POST / HTTP/1.1
Host: 127.0.0.1:9001
Authorization: AWS4-HMAC-SHA256 Credential=AV2MCXOUA9MY0KGHYFCQ/20171130/us-east-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=fbe6a86ebe82b6b175bee183e7fc5819ce0907639a66726c1a267af3ad375987
X-Amz-Date: 20171130T035937Z
User-Agent: amazon-kinesis-client-library-java-1.7.6 amazon-kinesis-multi-lang-daemon/1.0.1 golang sample,amazon-kinesis-client-library-java-1.7.6, aws-sdk-java/1.11.151 Linux/4.4.0-101-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.151-b12/1.8.0_151
amz-sdk-invocation-id: 0ef628f4-048a-e150-7748-7cd9253a871a
amz-sdk-retry: 2/95/490
X-Amz-Target: Kinesis_20131202.DescribeStream
Content-Type: application/x-amz-cbor-1.1
Content-Length: 18
Connection: Keep-Alive

jStreamNamedtest
127.000.000.001.09001-127.000.000.001.37792: HTTP/1.1 502 Bad Gateway

127.000.000.001.09001-127.000.000.001.37792: Server: BaseHTTP/0.3 Python/2.7.12

127.000.000.001.09001-127.000.000.001.37792: Date: Thu, 30 Nov 2017 03:59:37 GMT

127.000.000.001.09001-127.000.000.001.37792:
```

the post body is incorrect for `DescribeStream` request, so MultiLangDaemon get exception:

```shell
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:200)
	at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:95)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:150)
	at com.amazonaws.util.IOUtils.toByteArray(IOUtils.java:44)
	at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:48)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1570)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:1948)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:1924)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:720)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:696)
	at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getStreamInfo(KinesisProxy.java:181)
	at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getShardList(KinesisProxy.java:243)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.getShardList(ShardSyncer.java:288)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:112)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:88)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask.call(ShardSyncTask.java:68)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:427)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:356)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.call(MultiLangDaemon.java:114)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.call(MultiLangDaemon.java:61)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I am not a java programer.

 can someone help me debug it?

**Comment by pfifer** [comment]
There isn't much we can do to help.  This is either an issue with the [AWS Java SDK](https://github.com/aws/aws-sdk-java/) or with [LocalStack](https://github.com/localstack/localstack).  You would need to ask there. 

Feel free to reopen if you have more questions.
