### ISSUE TITLE
Timout exception while creating the leasetable

### ISSUE THREAD

**Issue by khaledsobhy83** [awslabs/amazon-kinesis-client#276]
I am getting timeout exception when KCL tries to connect to dynamodb to create the leasetable. I can connect and create tables to my dynamodb from AWS CLI but not using KCL. I have my credentials correct with the right access rights and my KCL.properties looks correct as well

Here is the exception details:

jan 08, 2018 12:54:20 EM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to dynamodb.eu-west-1.amazonaws.co
m:443 [dynamodb.eu-west-1.amazonaws.com/52.94.5.194] failed: connect timed out
org.apache.http.conn.ConnectTimeoutException: Connect to dynamodb.eu-west-1.amaz
onaws.com:443 [dynamodb.eu-west-1.amazonaws.com/52.94.5.194] failed: connect tim
ed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect
(DefaultHttpClientConnectionOperator.java:150)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(
PoolingHttpClientConnectionManager.java:353)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke
(ClientConnectionManagerFactory.java:76)
        at com.amazonaws.http.conn.$Proxy8.connect(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClie
ntExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.
java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java
:184)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
Client.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:55)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpCl
ient.java:72)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClien
t.java:858)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.ja
va:701)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:4
53)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient
.java:415)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:364
)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(Amazo
nDynamoDBClient.java:2048)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonD
ynamoDBClient.java:2018)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.createTable(Am
azonDynamoDBClient.java:878)
        at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTa
bleIfNotExists(LeaseManager.java:127)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClient
LibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:234)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initia
lize(Worker.java:415)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Wo
rker.java:356)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.call(MultiLa
ngDaemon.java:111)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.call(MultiLa
ngDaemon.java:58)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSL
ConnectionSocketFactory.java:337)
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSS
ocketFactory.java:132)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect
(DefaultHttpClientConnectionOperator.java:141)
        ... 32 more

**Comment by sahilpalvia** [comment]
Is this a persistent issue or a one off? Did you try using the AWS cli to create the DDB tables from the same host?

**Comment by khaledsobhy83** [comment]
Yes, It is a persistent issue and yes tried from AWS CLI and it worked very fine. It happens only when I use KCL.

**Comment by sahilpalvia** [comment]
Can you make sure to run the AWS CLI command from the same host where the KCL is running?

**Comment by khaledsobhy83** [comment]
I created so many dynamodb tables with AWS CLI on the same machine that KCL producing this issue and today I tried another machine and the same issue happened. I am sure it is happening only from KCL.
By the way, we have a proxy not sure if this requires any configurations.

**Comment by sahilpalvia** [comment]
And you are creating the tables in the same region "eu-west-1" or "EU (Ireland)" while using the cli?

I am not sure if there is proxy config that would be required for the cli vs the java sdk.

**Comment by pfifer** [comment]
The SDK does require the proxy configuration.  The proxy setting will also attempt to load from the Java system settings if present.  The proxy configuration can be explicitly set in the SDK's ClientConfiguration, you may need to initialize the DynamoDB client directly, and pass that client to the KCL.
