### ISSUE TITLE
LeaseKey cannot be null

### ISSUE THREAD

**Issue by chainhead** [awslabs/amazon-kinesis-client#298]
I am trying to replicate [this example](https://www.mongodb.com/blog/post/processing-data-streams-with-amazon-kinesis-and-mongodb-atlas) where, a Kinesis consumer processes a Kinesis stream and inserts into MonogDB. Firstly, it is not clear, what is the role of DynamoDB here. I was stuck with an DynamoDB exception around partition key and item name, etc. I was writing to the Kinesis stream as shown below.

```java
		// Write records to the stream.
		PutRecordRequest putRecordRequest = new PutRecordRequest();
		putRecordRequest.setStreamName(awsKinesisStreamName);
		putRecordRequest.setData(ByteBuffer.wrap(deviceData.getBytes()));
		//putRecordRequest.setPartitionKey(String.format("partitionKey-%d", createTime));
		putRecordRequest.setPartitionKey(String.format("deviceId-%s", deviceId));
		PutRecordResult putRecordResult = kinesis.putRecord(putRecordRequest);
		LOG.info(new String("SUCCESS. " + putRecordRequest.getPartitionKey() + " " + putRecordResult.getShardId() + " " + putRecordResult.getSequenceNumber()));
```
Now, I am stuck with `java.lang.IllegalArgumentException: LeaseKey cannot be set to null`. I just don't know, how to make progress here.

```
SEVERE: Caught exception while sync'ing Kinesis shards and leases
java.lang.IllegalArgumentException: LeaseKey cannot be set to null
	at com.amazonaws.services.kinesis.leases.impl.Lease.verifyNotNull(Lease.java:250)
	at com.amazonaws.services.kinesis.leases.impl.Lease.setLeaseKey(Lease.java:171)
	at com.amazonaws.services.kinesis.leases.impl.LeaseSerializer.fromDynamoRecord(LeaseSerializer.java:78)
	at com.amazonaws.services.kinesis.leases.impl.KinesisClientLeaseSerializer.fromDynamoRecord(KinesisClientLeaseSerializer.java:58)
	at com.amazonaws.services.kinesis.leases.impl.KinesisClientLeaseSerializer.fromDynamoRecord(KinesisClientLeaseSerializer.java:33)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.list(LeaseManager.java:255)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.listLeases(LeaseManager.java:214)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:119)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:88)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask.call(ShardSyncTask.java:68)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:439)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:372)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.call(MultiLangDaemon.java:114)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.call(MultiLangDaemon.java:61)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Please advise. Thanks!

**Comment by pfifer** [comment]
This can occur if the DynamoDB table is being used for two different streams.  Make sure you're not reusing the same application name for more than 1 stream.

DynamoDB is used to track which workers are processing which shards.  If two streams are sharing the table they will stomp on each other, and cause problems.

**Comment by chainhead** [comment]
I had two tables and one stream that I mixed/messed up. I have it working now. Thanks!
