### ISSUE TITLE
issues building project

### ISSUE THREAD

**Issue by BardiaAfshin** [awslabs/amazon-kinesis-client#30]
here's the command for building the cloned project, and the output

```bash
mvn clean install -Dpgpg.skip=true
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by kevincdeng** [comment]
Hi Bardia,

Are you using java 1.6? You need java 7 or higher, make sure JAVA_HOME is pointing to the correct place, it should look something like this:

```
# OSX
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/

# Linux
# echo $JAVA_HOME
/root/jdk1.8.0_45
```

**Comment by f-ganz** [comment]
I am having similar issues with the jar provided by maven. It seems it has been compiled with Java 1.8 and therefore throws UnsupportedClassVersionError when compiled in my Java 1.7 Project.

**Comment by jplock** [comment]
We ran into this as well.  I'm compiling my code with JDK7 and have the compiler plugin set to 1.7.  Everything compiles fine but it won't run under JRE7.

**Comment by manango** [comment]
@f-ganz and @jplock, thanks for reporting the issue. This issue exists with KCL 1.5.0 maven artifact. We will release the fix soon.

**Comment by kevincdeng** [comment]
1.5.1 is once again compiled with Java 7.
