### ISSUE TITLE
KCL library throwing error 

### ISSUE THREAD

**Issue by anmol1ratn** [awslabs/amazon-kinesis-client#348]
I implemented KCL using the example given in [AWS SDK samples](https://github.com/aws/aws-sdk-java/blob/master/src/samples/AmazonKinesis/AmazonKinesisApplicationSample.java)
The code for Main class is
```java
import com.amazonaws.AmazonClientException;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.kinesis.AmazonKinesis;
import com.amazonaws.services.kinesis.AmazonKinesisClientBuilder;
import com.amazonaws.services.kinesis.clientlibrary.interfaces.v2.IRecordProcessorFactory;
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitialPositionInStream;
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibConfiguration;
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker;
import com.amazonaws.services.kinesis.model.ResourceNotFoundException;

import java.net.InetAddress;
import java.util.UUID;

public class ApplicationMain {
    private static final String STREAM_NAME = "xxxxx";
    private static final String APPLICATION_NAME = "xxxxxxx";
    private static final InitialPositionInStream INITIAL_POSITION_IN_STREAM = InitialPositionInStream.LATEST;
    private static ProfileCredentialsProvider credentialsProvider;

    private static void init() {
        java.security.Security.setProperty("networkaddress.cache.ttl", "60");

        credentialsProvider = new ProfileCredentialsProvider("default");
        try {
            credentialsProvider.getCredentials();
        } catch (Exception e) {
            throw new AmazonClientException("Cannot load the credentials from the credential profiles file. "
                    + "Please make sure that your credentials file is at the correct "
                    + "location (~/.aws/credentials), and is in valid format.", e);
        }
    }

    private static void deleteResources() {
        AmazonKinesis kinesis = AmazonKinesisClientBuilder.standard()
                .withCredentials(credentialsProvider)
                .withRegion("us-west-2")
                .build();

        System.out.printf("Deleting the Amazon Kinesis stream used by the sample. Stream Name = %s.\n", STREAM_NAME);

        try {
            kinesis.deleteStream(STREAM_NAME);
        } catch (ResourceNotFoundException ex) {
            System.out.println("The stream doesn't exist.");
        }

        AmazonDynamoDB dynamoDB = AmazonDynamoDBClientBuilder.standard()
                .withCredentials(credentialsProvider)
                .withRegion("us-west-2")
                .build();
        System.out.printf("Deleting the Amazon DynamoDB table used by the Amazon Kinesis Client Library. Table Name = %s.\n",
                APPLICATION_NAME);
        try {
            dynamoDB.deleteTable(APPLICATION_NAME);
        } catch (com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException ex) {
            // The table doesn't exist.
        }
    }

    public static void main(String[] args) throws Exception {
        init();

        if (args.length == 1 && "delete-resources".equals(args[0])) {
            deleteResources();
            return;
        }

        String workerId = InetAddress.getLocalHost().getCanonicalHostName() + ":" + UUID.randomUUID();
        KinesisClientLibConfiguration kinesisClientLibConfiguration =
                new KinesisClientLibConfiguration(APPLICATION_NAME, STREAM_NAME, credentialsProvider, workerId);
        kinesisClientLibConfiguration.withInitialPositionInStream(INITIAL_POSITION_IN_STREAM);

        IRecordProcessorFactory recordProcessorFactory = new ApplicationRecordProcessorFactory();
        Worker worker = new Worker.Builder()
                .recordProcessorFactory(recordProcessorFactory)
                .config(kinesisClientLibConfiguration)
                .build();

        System.out.printf("Running %s to process stream %s as worker %s...\n", APPLICATION_NAME, STREAM_NAME, workerId);

        int exitCode = 0;
        try {
            worker.run();
        } catch (Throwable t) {
            System.err.println("Caught throwable while processing data.");
            t.printStackTrace();
            exitCode = 1;
        }
        System.exit(exitCode);
    }
}
```

But when I run the main() method, it throws the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableSet
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibConfiguration.<clinit>(KinesisClientLibConfiguration.java:112)
	at ApplicationMain.main(ApplicationMain.java:71)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableSet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

I'm using KCL version 1.9.1 and AWS SDK version 1.11.358
What am I doing wrong?

**Comment by anmol1ratn** [comment]
Hey, I downloaded Guava jar file and included it as a dependency in my project and it worked. :)
