### ISSUE TITLE
Error while executing Kinesis example

### ISSUE THREAD

**Issue by anmol1ratn** [awslabs/amazon-kinesis-client#350]
I'm making a project which involves recognizing faces in a streaming video for which I have to use Kinesis Client Library to read records from Kinesis Data Streams. I followed this [AmazonKinesisSample](https://github.com/aws/aws-sdk-java/tree/master/src/samples/AmazonKinesis) and wrote a KCL application to read data from Kinesis Stream. However I'm running into an error.
```
Running KinesisApplication to process stream AmazonRekognitionDataStream as worker anmol-pc:67de8011-3c46-4050-bde8-93dbd181765e...
Jul 25, 2018 5:56:34 PM com.amazonaws.services.kinesis.leases.impl.LeaseCoordinator <init>
INFO: With failover time 10000 ms and epsilon 25 ms, LeaseCoordinator will renew leases every 3308 ms, takeleases every 20050 ms, process maximum of 2147483647 leases and steal 1 lease(s) at a time.
Jul 25, 2018 5:56:34 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker initialize
INFO: Initialization attempt 1
Jul 25, 2018 5:56:34 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker initialize
INFO: Initializing LeaseCoordinator
Jul 25, 2018 5:56:36 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker initialize
INFO: Syncing Kinesis shard info
Jul 25, 2018 5:56:38 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker initialize
INFO: Starting LeaseCoordinator
Jul 25, 2018 5:56:49 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker run
INFO: Initialization complete. Starting worker loop.
Jul 25, 2018 5:56:59 PM com.amazonaws.services.kinesis.leases.impl.LeaseTaker computeLeasesToTake
INFO: Worker anmol-pc:67de8011-3c46-4050-bde8-93dbd181765e saw 1 total leases, 1 available leases, 1 workers. Target is 1 leases, I have 0 leases, I will take 1 leases
Jul 25, 2018 5:57:00 PM com.amazonaws.services.kinesis.leases.impl.LeaseTaker takeLeases
INFO: Worker anmol-pc:67de8011-3c46-4050-bde8-93dbd181765e successfully took 1 leases: shardId-000000000000
Jul 25, 2018 5:57:01 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker infoForce
INFO: Created new shardConsumer for : ShardInfo [shardId=shardId-000000000000, concurrencyToken=603e5409-c6c7-41f8-a271-ee51e1293e2e, parentShardIds=[], checkpoint={SequenceNumber: LATEST,SubsequenceNumber: 0}]
Jul 25, 2018 5:57:01 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.BlockOnParentShardTask call
INFO: No need to block on parents [] of shard shardId-000000000000
Jul 25, 2018 5:57:02 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher initialize
INFO: Initializing shard shardId-000000000000 with LATEST
Jul 25, 2018 5:57:04 PM ApplicationRecordProcessor initialize
INFO: Initializing record processor for shard: shardId-000000000000
Jul 25, 2018 5:57:34 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker info
INFO: Current stream shard assignments: shardId-000000000000
Jul 25, 2018 5:57:34 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker info
INFO: Sleeping ...
Jul 25, 2018 5:58:24 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker runProcessLoop
SEVERE: Worker.run caught exception, sleeping for 1000 milli seconds!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardConsumer.determineTaskOutcome(ShardConsumer.java:322)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardConsumer.checkAndSubmitNextTask(ShardConsumer.java:261)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardConsumer.consumeShard(ShardConsumer.java:249)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.runProcessLoop(Worker.java:591)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:574)
	at ApplicationMain.main(ApplicationMain.java:87)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardConsumer.determineTaskOutcome(ShardConsumer.java:313)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.deaggregateRecords(ProcessTask.java:256)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:168)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.InvalidProtocolBufferException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```
This problem is already posted by someone on AWS forum [here](https://forums.aws.amazon.com/thread.jspa?messageID=698750) but it is not answered. I think you guys might have some idea of what the problem is.

Thanks a ton in advance.

**Comment by anmol1ratn** [comment]
@pfifer , @sahilpalvia 
Would you please look into this, I have a deadline to meet? I can't get around this error.

Here's my code for [ApplicationRecordProcessor.java](https://codeshare.io/G8Vvoe) and [KinesisApplication.java](https://codeshare.io/am3eEk)

**Comment by sahilpalvia** [comment]
Seems like a mismatch with the protobuf library. 2.6.1 is what the KCL uses, you can find it here in the [pom.xml](https://github.com/awslabs/amazon-kinesis-client/blob/master/pom.xml#L58)

**Comment by anmol1ratn** [comment]
You're right. I created the dependencies once again and it worked!
Thanks a lot pal.
