### ISSUE TITLE
Kinesis Consumer(KCL v 1.9.0) - AmazonDynamoDBException while initializing LeaseCoordinator

### ISSUE THREAD

**Issue by sdhanavath** [awslabs/amazon-kinesis-client#351]
Hi,

Unable to initialize KCL worker... failing at initializing LeaseCoordinator... as shown below...

reaching out for help!

2018-07-29 17:01:31.987  INFO 3886 --- [           main] c.a.s.k.clientlibrary.lib.worker.Worker  : Initialization attempt 1
2018-07-29 17:01:31.987  INFO 3886 --- [           main] c.a.s.k.clientlibrary.lib.worker.Worker  : Initializing LeaseCoordinator
2018-07-29 17:01:32.661 ERROR 3886 --- [           main] c.a.s.kinesis.leases.impl.LeaseManager   : Failed to get table status for SmartConsumer

com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Request is missing Authentication Token (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: MissingAuthenticationTokenException; Request ID: NVNJQ91S0DV2LHGRT5LR0J1HUNVV4KQNSO5AEMVJF66Q9ASUAAJG)
        at com.amazonaws.services.kinesis.leases.impl.LeaseManager.tableStatus(LeaseManager.java:162) ~[amazon-kinesis-client-1.8.0.jar:na]
        at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:107) ~[amazon-kinesis-client-1.8.0.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:235) [amazon-kinesis-client-1.8.0.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:431) [amazon-kinesis-client-1.8.0.jar:na]
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:372) [amazon-kinesis-client-1.8.0.jar:na]
        at com.telstra.selfservice.smartconsumer.SmartCosumerApplication.main(SmartCosumerApplication.java:135) [classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_141]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_141]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_141]
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:496) [spring-boot-maven-plugin-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Request is missing Authentication Token (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: MissingAuthenticationTokenException; Request ID: NVNJQ91S0DV2LHGRT5LR0J1HUNVV4KQNSO5AEMVJF66Q9ASUAAJG)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.256.jar:na]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2925) ~[aws-java-sdk-dynamodb-1.11.256.jar:na]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2901) ~[aws-java-sdk-dynamodb-1.11.256.jar:na]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeDescribeTable(AmazonDynamoDBClient.java:1515) ~[aws-java-sdk-dynamodb-1.11.256.jar:na]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:1491) ~[aws-java-sdk-dynamodb-1.11.256.jar:na]
        at com.amazonaws.services.kinesis.leases.impl.LeaseManager.tableStatus(LeaseManager.java:154) ~[amazon-kinesis-client-1.8.0.jar:na]
        ... 11 common frames omitted

**Comment by pfifer** [comment]
It sounds like the DynamoDB client doesn't have the correct credentials.  

* If you're creating the DynamoDB client make sure you're supplying a valid AWSCredentialsProvider object
* If you're letting the KCL create the client make sure you're supplying a valid AWSCredentialsProvider to the configuration either the general credentials or the DynamoDB specific credentials.

Feel free to re-open if you have additional questions.

**Comment by sdhanavath** [comment]
Hi pfifer!

Thanks!
You are right, it was because I was passing `AWSStaticCredentialsProvider` type to `KinesisClientLibConfiguration`  instead of `AWSCredentialsProvider'  and that was causing DependencyException while creating DynamoDbClient...

Never/Don't use as below:
=================
AWSStaticCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(
				new BasicAWSCredentials(awsId, awsKey));

Recommended/correct way:
==================
AWSCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(
				new BasicAWSCredentials(awsId, awsKey));
