### ISSUE TITLE
Getting "java.lang.NoSuchFieldError: INSTANCE" after updating to latest AWS SDK

### ISSUE THREAD

**Issue by grepsr** [awslabs/amazon-kinesis-client#38]
I can't run the multilang daemon anymore, I keep getting the following error when I execute the following. This was working fine with the older version of the SDK.

python /home/kinesis/kcl/cmd_helper.py --print_command --java /usr/bin/java --properties app.properties --classpath /home/kinesis/aws-java-sdk-1.10.12/lib/aws-java-sdk-1.10.12.jar

``````
INFO: Initializing LeaseCoordinator
Aug 25, 2015 11:16:22 AM com.amazonaws.services.kinesis.multilang.MultiLangDaemon call
SEVERE: Caught throwable while processing data.
java.lang.NoSuchFieldError: INSTANCE
    at com.amazonaws.http.conn.SdkConnectionKeepAliveStrategy.getKeepAliveDuration(SdkConnectionKeepAliveStrategy.java:48)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:533)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:728)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1776)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.createTable(AmazonDynamoDBClient.java:822)
    at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:117)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:172)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:380)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:324)
    at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.call(MultiLangDaemon.java:104)
    at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.call(MultiLangDaemon.java:57)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)```
``````

**Comment by tomasiew** [comment]
Hi grepsr,

Is the cmd_helper.py script in your example similar to [amazon_kclpy_helper.py](https://github.com/awslabs/amazon-kinesis-client-python/blob/master/samples/amazon_kclpy_helper.py)?

If so, specifying the SDK 1.10 JAR with --classpath will result in it being *added* to the JVM classpath, which already contains JARs for the Java KCL and SDK. This means that you will have two SDK JARs on the classpath at different versions, which can result in the error you're seeing.

If you'd like to use a different version of the Java KCL or SDK (e.g. 1.10), you'll want to update the [Maven package versions in setup.py](https://github.com/awslabs/amazon-kinesis-client-python/blob/master/setup.py#L55) and re-run download_jars.

Keep in mind, we may not have tested the newest KCL/SDK versions with the Python KCL yet to ensure they are still compatible. If you run into more issues, you may need to switch back to the default versions.

Hope this helps!

**Comment by grepsr** [comment]
Hi tomasiew,

It turns out the Amazon Kinesis Python client (from pip) is outdated and does not work with the latest versions. I had to update the setup.py and re-install the python packages to make it work.

Now it works great!

I guess I should request to merge the changes into the Python client codebase. 

Thanks!

**Comment by smokey42** [comment]
The latest version which works for me is 1.10.11 which can be downloaded under http://sdk-for-java.amazonwebservices.com/aws-java-sdk-1.10.11.zip

**Comment by pfifer** [comment]
The newer versions of the client are now using 1.11.x of the AWS SDK.  

What you saw has all the hallmarks of a version mismatch between different components of the AWS SDK.

Please try the newer version of the Python library, and reopen if you have any issues.
