### ISSUE TITLE
ProvisionedThroughputExceededException in kinesis client library

### ISSUE THREAD

**Issue by rantav** [awslabs/amazon-kinesis-client#4]
Sometimes I see these errors in the logs. 
They don't happen a lot, but they do happen.
I suppose they mean that the kinesis client reads data too fast. 
I was under the impression that the client lib is supposed to take care of reading the data in the right pace, am I wrong?

Please advise....

```
ERROR [2014-09-12 13:52:33,150] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask: ShardId shardId-000000000002: Caught exception:
! com.amazonaws.services.kinesis.model.ProvisionedThroughputExceededException: Rate exceeded for stream gateway-filtered under account 671587110562. (Service: AmazonKinesis; Status Code: 400; Error Code: ProvisionedThroughputExceededException; Request ID: 0b75a25f-3a84-11e4-a1f8-cf42abe98da9)
! at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:820) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:439) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:245) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2128) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.AmazonKinesisClient.getRecords(AmazonKinesisClient.java:590) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.get(KinesisProxy.java:135) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.clientlibrary.proxies.MetricsCollectingKinesisProxyDecorator.get(MetricsCollectingKinesisProxyDecorator.java:72) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:69) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.getRecords(ProcessTask.java:186) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:96) ~[gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:48) [gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:23) [gateway-packager-8601271.jar:1.0-BETA-SNAPSHOT]
! at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_65]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
! at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
```

**Comment by NathanChristie** [comment]
I also support lowering this to the warning level.

**Comment by f-ganz** [comment]
+1

**Comment by preetpuri** [comment]
I agree this should be lower down to warn level

**Comment by SmiddyPence** [comment]
+1 For a Warn

**Comment by zackhsi** [comment]
+1

**Comment by pfifer** [comment]
Thanks for reporting this.  We'll look at handling the throttling exception, and reporting it at a lower logging level.

**Comment by pfifer** [comment]
This has been fixed in the latest release.  It will now be a warning unless it's throttled 6 times consecutively.  Additionally the message is now reported from the the ThrottleReporter if you want to filter it out completely. 

Feel free to reopen if you have any other questions or concerns.

**Comment by kirill-kozlov** [comment]
Hey, is it possible to migrate the implemented functionality to 2.X version also?
There is an open request about it: https://github.com/awslabs/amazon-kinesis-client/issues/539
