### ISSUE TITLE
MultiLangDaemon broken in 2.0.2? (credentials provider issues)

### ISSUE THREAD

**Issue by zerth** [awslabs/amazon-kinesis-client#404]
I see the following error and stack trace when specifying `software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider` (the new class replacing `DefaultAWSCredentialsProviderChain`) as the value of `AWSCredentialsProvider` in a MultiLangDaemon properties file (2.0.2):

Error:
```
2018-09-18 18:00:01,105 [main] DEBUG c.a.s.k.m.c.AWSCredentialsProviderPropertyValueDecoder [NONE] - Can't find any credentials provider matching software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.
```

Stack trace:
```
java.lang.InstantiationException: software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider 
java.lang.InstantiationException: software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider
	at java.lang.Class.newInstance(Class.java:423)
	at com.amazonaws.services.kinesis.multilang.config.AWSCredentialsProviderPropertyValueDecoder.getValidCredentialsProviders(AWSCredentialsProviderPropertyValueDecoder.java:91)
	at com.amazonaws.services.kinesis.multilang.config.AWSCredentialsProviderPropertyValueDecoder.decodeValue(AWSCredentialsProviderPropertyValueDecoder.java:52)
	at com.amazonaws.services.kinesis.multilang.config.AWSCredentialsProviderPropertyValueDecoder.decodeValue(AWSCredentialsProviderPropertyValueDecoder.java:29)
	at com.amazonaws.services.kinesis.multilang.config.KinesisClientLibConfigurator.getConfiguration(KinesisClientLibConfigurator.java:109)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:101)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:74)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:58)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:128)
Caused by: java.lang.NoSuchMethodException: software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3074)
	at java.lang.Class.newInstance(Class.java:408)
	... 8 more
```

Looking at the SDK v2 changelog, I see a number of constructor-related changes; example:
> new DefaultAWSCredentialsProviderChain is now DefaultCredentialsProvider.create.

After updating `com.amazonaws.services.kinesis.multilang.config.AWSCredentialsProviderPropertyValueDecoder` to use the new auth class prefix and `create` instance creation methods (using `getDeclaredMethod` and `invoke`), I successfully obtain an instance:
```
DefaultCredentialsProvider(providerChain=AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profiles=[Profile(name=default, properties=[s3])])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]))
```

However, continuing the initialization process results in an NPE here: https://github.com/awslabs/amazon-kinesis-client/blob/592499f7bc3cc1e23580688c82a3050913a62676/amazon-kinesis-client-multilang/src/main/java/com/amazonaws/services/kinesis/multilang/MultiLangDaemonConfig.java#L117 (`kinesisClientLibConfig.getKinesisCredentialsProvider()` is null, which matches the removals documented here: https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.html#client-configuration).

**Comment by sahilpalvia** [comment]
MultiLangDaemon support has been added after 2.1.0 version of the KCL. Please upgrade to the latest KCL.

Closing the issue out. Feel free to reopen if problem persists.
