### ISSUE TITLE
Executor service has been appeared continuously and no more get data from kinesis

### ISSUE THREAD

**Issue by sj3lee** [awslabs/amazon-kinesis-client#484]
I've been testing the producing/consuming with load today.
But the load test is over, I saw below error often.
Normally, this situation is coming when load test is over and a second is passed.

I set up PREFETCH_CACHED for dataFetching strategy

1. Sleeping and waiting data

Current stream shard assignments: shardId-000000000159, shardId-000000000156,
Sleeping 

2. Lost lease and try to renew lease
Worker A lost lease with key shardId-000000000156,

3. Shutdown was called on cache
=trieval.polling.PrefetchRecordsPublisher#run            :218  , message=Thread was interrupted, indicating shutdown was called on the cache.

4. Below error is coming * n times
03:55:46.118 +0000 | timestamp=03:55:46.118, level=ERROR, loggingId=, logger=trieval.polling.PrefetchRecordsPublisher#run            :229  , tn=pool-15-thread-1,  message=Unexpected exception was thrown. This could probably be an issue or a bug. Please search for the exception/error online to check what is going on. If the issue persists or is a recurring problem, feel free to open an issue on, https://github.com/awslabs/amazon-kinesis-client., java.lang.RuntimeException: java.lang.InterruptedException 	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:248) 	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:90) 	at software.amazon.kinesis.retrieval.polling.SynchronousGetRecordsRetrievalStrategy.getRecords(SynchronousGetRecordsRetrievalStrategy.java:34) 	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.run(PrefetchRecordsPublisher.java:204) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.InterruptedException: null 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347) 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) 	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:240) 	... 6 common frames omitted

5. Below error is also coming * n times
timestamp=03:55:47.082, level=ERROR, loggingId=, logger=trieval.polling.PrefetchRecordsPublisher#run            :229  , tn=pool-15-thread-2,  message=Unexpected exception was thrown. This could probably be an issue or a bug. Please search for the exception/error online to check what is going on. If the issue persists or is a recurring problem, feel free to open an issue on, https://github.com/awslabs/amazon-kinesis-client.,
java.lang.IllegalStateException: Shutdown has been called on the cache, can't accept new requests.
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.getNextResult(PrefetchRecordsPublisher.java:138)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.drainQueueForRequests(PrefetchRecordsPublisher.java:186)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.access$300(PrefetchRecordsPublisher.java:59)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.run(PrefetchRecordsPublisher.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

6. Above error is coming n times, after, repeat Executor service was shutdown
imestamp=03:55:49.119, level=ERROR, loggingId=, logger=.amazon.kinesis.lifecycle.InitializeTask#call           :115  , tn=ShardRecordProcessor-0006,  message=Caught exception: ,
java.lang.IllegalStateException: ExecutorService has been shutdown.
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.start(PrefetchRecordsPublisher.java:124)
	at software.amazon.kinesis.lifecycle.InitializeTask.call(InitializeTask.java:83)
	at software.amazon.kinesis.lifecycle.ShardConsumer.executeTask(ShardConsumer.java:399)
	at software.amazon.kinesis.lifecycle.ShardConsumer.lambda$initializeComplete$2(ShardConsumer.java:353)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

6 error is occuring continuously and if I want to get any more data,I should restart application,
And sometimes another instance has been falling this situation also.
I using three instances, and I think only one instance has this error, and if I restart that instance, renew lease is coming and another instance has falling this error also.
Please find out what is the issue

**Comment by sj3lee** [comment]
@sahilpalvia, @pfifer 
Could you check this?
I think this issue is coming when we control the number of shard on console or UpdateShardCount api.
This is appeared frequently.
Please let us know how can we resolve this issue

Thank you.
