### ISSUE TITLE
KCL 2.1.0  doesn't call the record processor if used along with KPL 0.12.11 in the same POM file. The below exception gets thrown 

### ISSUE THREAD

**Issue by kiransahoo1980** [awslabs/amazon-kinesis-client#487]
Exception in thread "main" java.lang.NoSuchFieldError: UPPER_CAMEL_CASE
	at software.amazon.awssdk.core.internal.protocol.json.JsonErrorUnmarshaller.<clinit>(JsonErrorUnmarshaller.java:33)
	at software.amazon.awssdk.awscore.protocol.json.AwsJsonProtocolFactory.createErrorUnmarshallers(AwsJsonProtocolFactory.java:105)
	at software.amazon.awssdk.awscore.protocol.json.AwsJsonProtocolFactory.<init>(AwsJsonProtocolFactory.java:59)
	at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClient.init(DefaultKinesisAsyncClient.java:2270)
	at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClient.<init>(DefaultKinesisAsyncClient.java:199)
	at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClientBuilder.buildClient(DefaultKinesisAsyncClientBuilder.java:28)
	at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClientBuilder.buildClient(DefaultKinesisAsyncClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:118)
	at org.examples.java.SampleSingle.<init>(SampleSingle.java:86)
	at org.examples.java.SampleSingle.main(SampleSingle.java:76)

**Comment by kiransahoo1980** [comment]
If I am using KPL 0.12.11 and KCL 2.1.0 in the same pom. I have to explicitly add the jackson libraries as shown below to fix the exception and issues related to recordprocessor not getting called.

   <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.7</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-cbor</artifactId>
            <version>2.9.7</version>
        </dependency
