### ISSUE TITLE
Fatal error in scheduler when starting the scheduler

### ISSUE THREAD

**Issue by mresposito** [awslabs/amazon-kinesis-client#503]
I was trying to deploy my consumer library today, but it broke with this cryptic message. I'm currently running on 2.1.1. Yesterday it was working like a charm, but I can't get it to work anymore.

Any clue? I can't deploy the consumers due to this issue.

```
[error] s.a.k.l.ShardSyncTask - Caught exception while sync'ing Kinesis shards and leases
java.lang.RuntimeException: software.amazon.awssdk.core.exception.SdkClientException
        at software.amazon.kinesis.retrieval.AWSExceptionManager.apply(AWSExceptionManager.java:65)
        at software.amazon.kinesis.leases.KinesisShardDetector.listShards(KinesisShardDetector.java:172)
        at software.amazon.kinesis.leases.KinesisShardDetector.listShards(KinesisShardDetector.java:132)
        at software.amazon.kinesis.leases.HierarchicalShardSyncer.getShardList(HierarchicalShardSyncer.java:248)
        at software.amazon.kinesis.leases.HierarchicalShardSyncer.checkAndCreateLeaseForNewShards(HierarchicalShardSyncer.java:81)
        at software.amazon.kinesis.leases.ShardSyncTask.call(ShardSyncTask.java:67)
        at software.amazon.kinesis.metrics.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:53)
        at software.amazon.kinesis.coordinator.Scheduler.initialize(Scheduler.java:247)
        at software.amazon.kinesis.coordinator.Scheduler.run(Scheduler.java:213)
        at java.lang.Thread.run(Thread.java:748)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: null
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
        at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:118)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:104)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$1(MakeAsyncHttpRequestStage.java:136)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
Caused by: java.lang.NoSuchFieldError: NO_INTS
        at com.fasterxml.jackson.dataformat.cbor.CBORParser.<init>(CBORParser.java:285)
        at com.fasterxml.jackson.dataformat.cbor.CBORParserBootstrapper.constructParser(CBORParserBootstrapper.java:91)
        at com.fasterxml.jackson.dataformat.cbor.CBORFactory._createParser(CBORFactory.java:365)
        at com.fasterxml.jackson.dataformat.cbor.CBORFactory.createParser(CBORFactory.java:290)
        at com.fasterxml.jackson.dataformat.cbor.CBORFactory.createParser(CBORFactory.java:26)
        at software.amazon.awssdk.protocols.json.internal.dom.JsonDomParser.parse(JsonDomParser.java:39)
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:167)
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:79)
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
        at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)```

**Comment by pfifer** [comment]
You have conflicting versions of the Jackson libraries.  If you're using the 1.11 AWS Java SDK you need to ensure that the older version of Jackson are excluded by adding an exclusion element to the dependency bringing in the older version.  Here is an example of the exclusion to add to the `<dependency>` element:

``` xml
    <dependency>
      <groupId>...</groupId>
      <artifactId>...</artifactId>
      <version>...</version>
      <exclusions>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.dataformat</groupId>
          <artifactId>jackson-dataformat-cbor</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.dataformat</groupId>
          <artifactId>jackson-annotations</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

A quick way to find who is including the older version of Jackson is the command `mvn dependency:tree` which will print the dependency tree.  You need to make sure that the Jackson version matches what the [AWS Java SDK 2.x expects which I believe is 2.9.8 from the parent pom](https://search.maven.org/artifact/software.amazon.awssdk/aws-sdk-java-pom/2.4.8/pom).

Feel free to reopen this if you have more questions.

**Comment by mresposito** [comment]
Thanks for your help @pfifer, that did the trick!

Let me know if there is anything I can help you guys in this project, I love Kinesis service. I actually use Scala for my work, so if you all think it would be valuable I'd be happy to create an open-source Scala binding for it.

**Comment by GagandeepS** [comment]
Hi @mresposito @pfifer I am using spark streaming 2.4.5 but getting the same errors. I am using aws sdk 1.11.745 and jackson 2.10.0

Any idea what combination of version I should use?
