### ISSUE TITLE
ShardSyncTask fails after deregistering consumer from fanout

### ISSUE THREAD

**Issue by saeedansari** [awslabs/amazon-kinesis-client#508]
We have consumer using fanout feature to consume from a stream. We also have configuration in place to deregister consumers from fanout. After changing the configuration and deregister this consumer from fanout, we get following error:

```
2019-02-15 15:00:00.902 [ShardSyncTaskManager-0000] ERROR    s.a.k.leases.ShardSyncTask.call - Caught exception while sync'ing Kinesis shards and leases
software.amazon.kinesis.exceptions.internal.KinesisClientLibIOException: Shard [shardId-000000000000] is not closed. This can happen if we constructed the list of shards  while a reshard operation was in progress.
	at software.amazon.kinesis.leases.HierarchicalShardSyncer.assertClosedShardsAreCoveredOrAbsent(HierarchicalShardSyncer.java:172)
	at software.amazon.kinesis.leases.HierarchicalShardSyncer.cleanupLeasesOfFinishedShards(HierarchicalShardSyncer.java:599)
	at software.amazon.kinesis.leases.HierarchicalShardSyncer.checkAndCreateLeaseForNewShards(HierarchicalShardSyncer.java:112)
	at software.amazon.kinesis.leases.ShardSyncTask.call(ShardSyncTask.java:67)
	at software.amazon.kinesis.metrics.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:53)
	at software.amazon.kinesis.metrics.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-02-15 15:00:01.106 [Thread-9] ERROR    s.a.k.l.ShardSyncTaskManager.checkAndSubmitNextTask - Caught exception running SHARDSYNC task: 
software.amazon.kinesis.exceptions.internal.KinesisClientLibIOException: Shard [shardId-000000000000] is not closed. This can happen if we constructed the list of shards  while a reshard operation was in progress.
	at software.amazon.kinesis.leases.HierarchicalShardSyncer.assertClosedShardsAreCoveredOrAbsent(HierarchicalShardSyncer.java:172)
	at software.amazon.kinesis.leases.HierarchicalShardSyncer.cleanupLeasesOfFinishedShards(HierarchicalShardSyncer.java:599)
	at software.amazon.kinesis.leases.HierarchicalShardSyncer.checkAndCreateLeaseForNewShards(HierarchicalShardSyncer.java:112)
	at software.amazon.kinesis.leases.ShardSyncTask.call(ShardSyncTask.java:67)
	at software.amazon.kinesis.metrics.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:53)
	at software.amazon.kinesis.metrics.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I am aware that this error can happen during resharding when consumer still reads from parent shard, but could it also occur during deregistration while consumer still reading messages?
 
P.S: we changed back configuration to use fanout to solve this problem.

**Comment by sahilpalvia** [comment]
Could you provide more information about your usage? When does the application deregister the consumer? Is it at shutdown? Is the KCL still running at the same time?
