### ISSUE TITLE
KCL 2.x error massages 

### ISSUE THREAD

**Issue by SargisNBC** [awslabs/amazon-kinesis-client#529]
We are using consumer with Enhanced Fan-Out  KCL 2.1.2 time after time we get errors that are internal for KCL. wonder what is the reason.

	 timestamp:	 2019-03-27T22:27:56.658+00:00	
  	 class:	 s.a.k.r.fanout.FanOutRecordsPublisher	
  	 message:	 shardId-000000000001: [SubscriptionLifetime] - (FanOutRecordsPublisher#errorOccurred) @ 2019-03-27T22:26:28.382Z id: shardId-000000000001-1613 -- software.amazon.awssdk.services.kinesis.model.InternalFailureException: Internal Service Error (Service: kinesis, Status Code: 500, Request ID: c07479c2-3071-1c3a-9561-8316a39bf285)	
  	 stack_trace:	 s.a.a.s.k.m.InternalFailureException: Internal Service Error (Service: kinesis, Status Code: 500, Request ID: c07479c2-3071-1c3a-9561-8316a39bf285)
	at s.a.a.s.k.m.InternalFailureException$BuilderImpl.build(InternalFailureException.java:100)
	at s.a.a.s.k.m.InternalFailureException$BuilderImpl.build(InternalFailureException.java:60)
	at s.a.a.a.h.r.AwsJsonErrorResponseHandler.handle(AwsJsonErrorResponseHandler.java:86)
	at s.a.a.a.h.r.AwsJsonErrorResponseHandler.handle(AwsJsonErrorResponseHandler.java:37)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer.handleMessage(EventStreamAsyncResponseTransformer.java:292)
	at s.a.e.MessageDecoder.feed(MessageDecoder.java:74)
	at s.a.e.MessageDecoder.feed(MessageDecoder.java:34)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer$ByteSubscriber.onNext(EventStreamAsyncResponseTransformer.java:376)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer$ByteSubscriber.onNext(EventStreamAsyncResponseTransformer.java:352)
	at s.a.a.h.n.n.i.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:233)
	... 66 frames truncated

     timestamp:	 2019-03-27T22:27:56.659+00:00	
  	 class:	 s.amazon.kinesis.lifecycle.ShardConsumer	
  	 message:	 shardId-000000000001: onError().  Cancelling subscription, and marking self as failed.	
  	 stack_trace:	 s.a.a.s.k.m.InternalFailureException: Internal Service Error (Service: kinesis, Status Code: 500, Request ID: c07479c2-3071-1c3a-9561-8316a39bf285)
	at s.a.a.s.k.m.InternalFailureException$BuilderImpl.build(InternalFailureException.java:100)
	at s.a.a.s.k.m.InternalFailureException$BuilderImpl.build(InternalFailureException.java:60)
	at s.a.a.a.h.r.AwsJsonErrorResponseHandler.handle(AwsJsonErrorResponseHandler.java:86)
	at s.a.a.a.h.r.AwsJsonErrorResponseHandler.handle(AwsJsonErrorResponseHandler.java:37)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer.handleMessage(EventStreamAsyncResponseTransformer.java:292)
	at s.a.e.MessageDecoder.feed(MessageDecoder.java:74)
	at s.a.e.MessageDecoder.feed(MessageDecoder.java:34)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer$ByteSubscriber.onNext(EventStreamAsyncResponseTransformer.java:376)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer$ByteSubscriber.onNext(EventStreamAsyncResponseTransformer.java:352)
	at s.a.a.h.n.n.i.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:233)
	... 66 frames truncated

     timestamp:	 2019-03-27T22:27:57.278+00:00		
  	 class:	 s.amazon.kinesis.lifecycle.ShardConsumer	
  	 message:	 shardId-000000000001: Failure occurred in retrieval.  Restarting data requests	
  	 stack_trace:	 s.a.a.s.k.m.InternalFailureException: Internal Service Error (Service: kinesis, Status Code: 500, Request ID: c07479c2-3071-1c3a-9561-8316a39bf285)
	at s.a.a.s.k.m.InternalFailureException$BuilderImpl.build(InternalFailureException.java:100)
	at s.a.a.s.k.m.InternalFailureException$BuilderImpl.build(InternalFailureException.java:60)
	at s.a.a.a.h.r.AwsJsonErrorResponseHandler.handle(AwsJsonErrorResponseHandler.java:86)
	at s.a.a.a.h.r.AwsJsonErrorResponseHandler.handle(AwsJsonErrorResponseHandler.java:37)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer.handleMessage(EventStreamAsyncResponseTransformer.java:292)
	at s.a.e.MessageDecoder.feed(MessageDecoder.java:74)
	at s.a.e.MessageDecoder.feed(MessageDecoder.java:34)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer$ByteSubscriber.onNext(EventStreamAsyncResponseTransformer.java:376)
	at s.a.a.a.e.EventStreamAsyncResponseTransformer$ByteSubscriber.onNext(EventStreamAsyncResponseTransformer.java:352)
	at s.a.a.h.n.n.i.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:233)
	... 66 frames truncated

**Comment by Cory-Bradshaw** [comment]
The logs you have shared appear to be Kinesis server side errors, which the KCL will gracefully handle. These messages are informing you that the lease of the shard is being transferred to another KCL worker thread due to an unexpected Kinesis Server side error. Processing should resume on that shard as expected, however it may be processed by a different instance/host or be picked up by another thread on the same instance/host .

Are the logs you are seeing here confusing given their wording/severity?

Are you concerned about the impact of these errors on the propagation delay on your streams?

**Comment by adrian-baker** [comment]
In general, anything logged at WARN or ERROR is concerning. If this is a normal occurrence that doesn't cause an issue, and that the client user can do nothing about, it should be logged at INFO, or better, DEBUG.
