### ISSUE TITLE
Intermittent DynamoDb lease exceptions

### ISSUE THREAD

**Issue by ASharma0502** [awslabs/amazon-kinesis-client#564]
Hi,

We are using kinesis library, and we get  DynamoDb lease exceptions intermittently. Exception,  Encountered an exception while renewing a lease and LeasingException encountered in lease renewing thread occur in succession. Does this cause any loss of records ?

2019-06-24 04:47:09,215 [LeaseCoordinator-0006] ERROR s.a.kinesis.leases.dynamodb.DynamoDBLeaseRenewer - Encountered an exception while renewing a lease. LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
software.amazon.kinesis.leases.exceptions.DependencyException: software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException: Internal server error (Service: DynamoDB, Status Code: 500, Request ID: D76QM768H8IUJ7KBCJOF8BIV07VV4KQNSO5AEMVJF66Q9ASUAAJG) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRefresher.renewLease(DynamoDBLeaseRefresher.java:418) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer.renewLease(DynamoDBLeaseRenewer.java:183) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer.renewLease(DynamoDBLeaseRenewer.java:163) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer.access$000(DynamoDBLeaseRenewer.java:55) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer$RenewLeaseTask.call(DynamoDBLeaseRenewer.java:158) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer$RenewLeaseTask.call(DynamoDBLeaseRenewer.java:152) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.FutureTask.run(FutureTask.java:266) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.lang.Thread.run(Thread.java:748) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
Caused by: software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException: Internal server error (Service: DynamoDB, Status Code: 500, Request ID: D76QM768H8IUJ7KBCJOF8BIV07VV4KQNSO5AEMVJF66Q9ASUAAJG) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException$BuilderImpl.build(InternalServerErrorException.java:103) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException$BuilderImpl.build(InternalServerErrorException.java:63) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.response.SdkErrorResponseHandler.handle(SdkErrorResponseHandler.java:46) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.response.SdkErrorResponseHandler.handle(SdkErrorResponseHandler.java:30) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.async.SyncResponseHandlerAdapter.complete(SyncResponseHandlerAdapter.java:92) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.client.handler.BaseAsyncClientHandler$InterceptorCallingHttpResponseHandler.complete(BaseAsyncClientHandler.java:225) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.handleResponse(MakeAsyncHttpRequestStage.java:185) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.complete(MakeAsyncHttpRequestStage.java:171) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.complete(MakeAsyncHttpRequestStage.java:122) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:262) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher.publishMessage(HandlerPublisher.java:362) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher.flushBuffer(HandlerPublisher.java:304) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:258) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:452) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   ... 1 common frames omitted LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber

2019-06-24 04:47:09,215 [LeaseCoordinator-0006] ERROR s.a.k.leases.dynamodb.DynamoDBLeaseCoordinator - LeasingException encountered in lease renewing thread LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
software.amazon.kinesis.leases.exceptions.DependencyException: Encountered an exception while renewing leases. The number of leases which might not have been renewed is 1 LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer.renewLeases(DynamoDBLeaseRenewer.java:140) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseCoordinator.runLeaseRenewer(DynamoDBLeaseCoordinator.java:273) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseCoordinator$RenewerRunnable.run(DynamoDBLeaseCoordinator.java:200) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.lang.Thread.run(Thread.java:748) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
Caused by: java.util.concurrent.ExecutionException: software.amazon.kinesis.leases.exceptions.DependencyException: software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException: Internal server error (Service: DynamoDB, Status Code: 500, Request ID: D76QM768H8IUJ7KBCJOF8BIV07VV4KQNSO5AEMVJF66Q9ASUAAJG) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.FutureTask.report(FutureTask.java:122) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.FutureTask.get(FutureTask.java:192) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer.renewLeases(DynamoDBLeaseRenewer.java:122) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   ... 9 common frames omitted LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
Caused by: software.amazon.kinesis.leases.exceptions.DependencyException: software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException: Internal server error (Service: DynamoDB, Status Code: 500, Request ID: D76QM768H8IUJ7KBCJOF8BIV07VV4KQNSO5AEMVJF66Q9ASUAAJG) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRefresher.renewLease(DynamoDBLeaseRefresher.java:418) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer.renewLease(DynamoDBLeaseRenewer.java:183) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer.renewLease(DynamoDBLeaseRenewer.java:163) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer.access$000(DynamoDBLeaseRenewer.java:55) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer$RenewLeaseTask.call(DynamoDBLeaseRenewer.java:158) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRenewer$RenewLeaseTask.call(DynamoDBLeaseRenewer.java:152) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at java.util.concurrent.FutureTask.run(FutureTask.java:266) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   ... 3 common frames omitted LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
Caused by: software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException: Internal server error (Service: DynamoDB, Status Code: 500, Request ID: D76QM768H8IUJ7KBCJOF8BIV07VV4KQNSO5AEMVJF66Q9ASUAAJG) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException$BuilderImpl.build(InternalServerErrorException.java:103) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException$BuilderImpl.build(InternalServerErrorException.java:63) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.response.SdkErrorResponseHandler.handle(SdkErrorResponseHandler.java:46) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.response.SdkErrorResponseHandler.handle(SdkErrorResponseHandler.java:30) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.async.SyncResponseHandlerAdapter.complete(SyncResponseHandlerAdapter.java:92) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.client.handler.BaseAsyncClientHandler$InterceptorCallingHttpResponseHandler.complete(BaseAsyncClientHandler.java:225) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.handleResponse(MakeAsyncHttpRequestStage.java:185) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.complete(MakeAsyncHttpRequestStage.java:171) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.complete(MakeAsyncHttpRequestStage.java:122) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:262) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher.publishMessage(HandlerPublisher.java:362) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher.flushBuffer(HandlerPublisher.java:304) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:258) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:452) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber
   ... 1 common frames omitted LogGroup=prod-appName LogStream=ecs/appName/LogStreamNumber

**Comment by anoopgarlapati** [comment]
This issue was faced by others as well. You can follow it here #153. 

Quoting what could've went wrong from that thread:
> There isn't much this is indicating something went wrong talking to DynamoDB. If it's happening a lot inspect the underlying cause. If it's an internal service error we aren't able to do much, and in that case the best option is to contact DynamoDB and have them investigate the table. You can also investigate the metrics for your table to ensure that calls aren't getting throttled. DynamoDB also has a metric for system errors that I would check.
This exception occurs it indicates that the KCL was unable to renew the lease due to an issue calling UpdateItem on the application's lease table. When this occurs the KCL will assume its lost the lease and will shutdown the record processor with ZOMBIE.

**Comment by brendan-p-lynch** [comment]
Closing due to duplicate issue in #153
