### ISSUE TITLE
Missing stream leads to NullPointerException

### ISSUE THREAD

**Issue by pmogren** [awslabs/amazon-kinesis-client#6]
If the KCL is configured with a stream name that does not exist in the AWS account, once the retry logic gives up, I would expect a helpful exception from the com.amazonaws.services.kinesis.clientlibrary.exceptions package to be thrown. Instead, I get:

<pre><code>java.lang.NullPointerException
    at com.amazonaws.services.kinesis.leases.impl.LeaseCoordinator.stop(LeaseCoordinator.java:230)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:366)</code></pre>

**Comment by pfifer** [comment]
Thanks for reporting this. This has been fixed in newer versions of the library.  

Please reopen if you're still having issues.
