### ISSUE TITLE
KCL "Failed to initialize a channel" error

### ISSUE THREAD

**Issue by markthegrea** [awslabs/amazon-kinesis-client#613]
I am attempting to use Amazon KCL2 library to read from a Kinesis stream.  Specifically I am using these jars:

```
        <dependency>
          <groupId>software.amazon.kinesis</groupId>
          <artifactId>amazon-kinesis-client</artifactId>
          <version>2.1.1</version>
        </dependency>
```

The lease coordinator starts up fine but I get this error:

```
    2019-09-19T20:41:54.810|WARN |ChannelInitializer|exceptionCaught|97|Failed to initialize a channel. Closing: [id: 0x10114f31]
     java.lang.IllegalStateException: failed to build a Http2ConnectionHandler
    	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.buildFromCodec(ForkedHttp2MultiplexCodecBuilder.java:189)
    	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.buildFromConnection(ForkedHttp2MultiplexCodecBuilder.java:179)
    	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.build(ForkedHttp2MultiplexCodecBuilder.java:153)
    	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.configureHttp2(ChannelPipelineInitializer.java:104)2019-09-19T20:41:54.865|WARN |ChannelInitializer|exceptionCaught|97|Failed to initialize a channel. Closing: [id: 0xd09c9385]

```
When I dig down in there is a bigger problem:

    detailMessage = "io.netty.handler.codec.http2.Http2FrameCodec.<init>(Lio/netty/handler/codec/http2/Http2ConnectionEncoder;Lio/netty/handler/codec/http2/Http2ConnectionDecoder;Lio/netty/handler/codec/http2/Http2Settings;)V"
    cause = {NoSuchMethodError@8727} "java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2FrameCodec.<init>(Lio/netty/handler/codec/http2/Http2ConnectionEncoder;Lio/netty/handler/codec/http2/Http2ConnectionDecoder;Lio/netty/handler/codec/http2/Http2Settings;)V"

I have tried numerous other versions and added these:

    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-all</artifactId>
      <version>4.1.32.Final</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.2</version>
      <scope>runtime</scope>
    </dependency>

My code is just standard stuff (from the one web page with an example):

>     public void run() {
>         StopWatch sw = StopWatch.createStarted();
>         DynamoDbAsyncClient dynamoClient = DynamoDbAsyncClient.builder().region(region).build();
>         CloudWatchAsyncClient cloudWatchClient = CloudWatchAsyncClient.builder().region(region).build();
>         ConfigsBuilder configsBuilder = new ConfigsBuilder(streamName, "MessageSteward", kinesisClient,
>                                                            dynamoClient, cloudWatchClient,
>                                                            UUID.randomUUID().toString(),
>                                                            factory);
>     
>         InitialPositionInStreamExtended initPosition = InitialPositionInStreamExtended
>             .newInitialPosition(InitialPositionInStream.LATEST);
>     
>         Scheduler scheduler = new Scheduler(
>             configsBuilder.checkpointConfig(),
>             configsBuilder.coordinatorConfig(),
>             configsBuilder.leaseManagementConfig().initialPositionInStream(initPosition),
>             configsBuilder.lifecycleConfig(),
>             configsBuilder.metricsConfig(),
>             configsBuilder.processorConfig(),
>             configsBuilder.retrievalConfig()
>                 .retrievalSpecificConfig(new PollingConfig(streamName, kinesisClient))
>                 .initialPositionInStreamExtended(initPosition)
>         );
>     
>         Thread schedulerThread = new Thread(scheduler);
>         schedulerThread.setDaemon(true);
>         schedulerThread.start();
>     
>         LOG.info("Kinesis Reader started:({}ms) stream:{} - region:{}", sw.getTime(), this.streamName,
>                  this.region.toString());
>     
>         while (true) {
>           try {
>             Thread.sleep(5000);
>           } catch (InterruptedException e) {
>             LOG.error("Failed to sleep!");
>           }
>         }

Googling has not helped.  Anyone have any idea how to fix this?

**Comment by vladimirbilous** [comment]
Hi, @markthegrea 
I have a similar issue. You probably have some dependency(rather than this kinesis client)  that transitively load netty-codec-http2. In my case, it's Spring Boot dependency.
After the version 4.1.35.Final of netty-codec-http2 Http2FrameCodec class constructor signature has been changed. 
As a workaround, you can try to simply override the version of netty-codec-http2 to use the latest working one in your project pom:
```	
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-codec-http2</artifactId>
    <version>4.1.35.Final</version>
</dependency>
```

**Comment by markthegrea** [comment]
@vladimirbilous That did it.  Thanks!

**Comment by jlj0n3s** [comment]
I have the same issue, not resolved by adding the netty dependency.

I tried adding latest netty dependency:

       <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http2</artifactId>
            <version>4.1.48.Final</version>
        </dependency>

Still getting same error

2020-04-13 16:32:54,713 [aws-java-sdk-NettyEventLoop-1-4] WARN  io.netty.channel.ChannelInitializer  - Failed to initialize a channel. Closing: [id: 0x28bba709]
java.lang.IllegalStateException: failed to build a Http2ConnectionHandler
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.buildFromCodec(ForkedHttp2MultiplexCodecBuilder.java:189)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.buildFromConnection(ForkedHttp2MultiplexCodecBuilder.java:179)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.build(ForkedHttp2MultiplexCodecBuilder.java:153)
	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.configureHttp2(ChannelPipelineInitializer.java:125)
	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.channelCreated(ChannelPipelineInitializer.java:85)
	at io.netty.channel.pool.SimpleChannelPool$1.initChannel(SimpleChannelPool.java:113)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2FrameCodec.<init>(Lio/netty/handler/codec/http2/Http2ConnectionEncoder;Lio/netty/handler/codec/http2/Http2ConnectionDecoder;Lio/netty/handler/codec/http2/Http2Settings;)V
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodec.<init>(ForkedHttp2MultiplexCodec.java:171)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.build(ForkedHttp2MultiplexCodecBuilder.java:203)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.buildFromCodec(ForkedHttp2MultiplexCodecBuilder.java:185)
	... 23 common frames omitted

**Comment by v-bilous** [comment]
Hi @jlj0n3s ,
try with the version provided in my comment – <version>4.1.35.Final</version>
