### ISSUE TITLE
Null Pointer Exception when running syncing DynamoDB and ElasticSearch

### ISSUE THREAD

**Issue by paragshar** [awslabs/amazon-kinesis-client#62]
Dear all,
I am getting the following NullPointerException when running Logstash with multiple streams. However with one or two streams, it does not give such an issue.

`java.lang.NullPointerException
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.getCheckpoint(KinesisClientLibLeaseCoordinator.java:139)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask.call(InitializeTask.java:75)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by antony9** [comment]
I have the same issue with you...

Looking forward to the solution

**Comment by pfifer** [comment]
Are you using the same lease table for multiple Kinesis streams?  Each DynamoDB lease table can only be used with one stream.
