### ISSUE TITLE
First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f

### ISSUE THREAD

**Issue by rajuraog** [awslabs/amazon-kinesis-client#620]
I am trying to implement enhanced fan-out consumers(**java**) using KCL2 library. I have maven setup with below dependency.

**Maven Configuration**
```
<dependency>
	<groupId>software.amazon.kinesis</groupId>
	<artifactId>amazon-kinesis-client</artifactId>
	<version>2.2.4</version>
</dependency>
```

I using the same sample code given in https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html document. But as soon as I launch the application encountering the below exception.

`Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodec.channelRead(ForkedHttp2MultiplexCodec.java:359)`

**Note:** If I configure the same sample code to use HTTP1_1 protocol - it's working, am able to consume records from kinesis stream.
```
KinesisAsyncClient.builder()
                .httpClient(NettyNioAsyncHttpClient.builder().protocol(Protocol.HTTP1_1).build())
                .region(Region.of(kinesisRegion)).build();
```

**Comment by rajuraog** [comment]
Closed this issue - it was the network which causing it.

**Comment by samarprakash** [comment]
@rajuraog, could you please explain how did you resolve this issue? I'm facing same issue while using S3AsyncClient with HTTP/2 configuration to download the file
