### ISSUE TITLE
MultiLangDaemon Exception

### ISSUE THREAD

**Issue by jns4u** [awslabs/amazon-kinesis-client#633]
Hi

I implemented a kinesis stream consumer client using node wrapper and getting this MultiLangDaemon execution error

`Starting MultiLangDaemon ...
java.lang.IllegalArgumentException: No enum constant software.amazon.kinesis.common.InitialPositionInStream.TRIM_HORIZON
        at java.lang.Enum.valueOf(Enum.java:238)
        at software.amazon.kinesis.common.InitialPositionInStream.valueOf(InitialPositionInStream.java:21)
        at software.amazon.kinesis.multilang.config.MultiLangDaemonConfiguration$2.convert(MultiLangDaemonConfiguration.java:208)
        at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:491)
        at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1007)
        at software.amazon.kinesis.multilang.config.KinesisClientLibConfigurator.lambda$getConfiguration$0(KinesisClientLibConfigurator.java:65)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2064)
        at software.amazon.kinesis.multilang.config.KinesisClientLibConfigurator.getConfiguration(KinesisClientLibConfigurator.java:63)
        at software.amazon.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:101)
        at software.amazon.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:74)
        at software.amazon.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:58)
        at software.amazon.kinesis.multilang.MultiLangDaemon.buildMultiLangDaemonConfig(MultiLangDaemon.java:171)
        at software.amazon.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:220)
No enum constant software.amazon.kinesis.common.InitialPositionInStream.TRIM_HORIZON
`

I already cross checked properties file with details shown below listed there 
initialPositionInStream, processingLanguage,streamName,executableName etc.

TRIM_HORIZON is set as value for initialPositionInStream Not sure why software.amazon.kinesis.common.InitialPositionInStream this object missing this value?

Version:
Node: 12.11.0
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
OS: Amazon Linux AMI

Error Screenshot:
![image](https://user-images.githubusercontent.com/14173650/67265790-3d45c880-f4cc-11e9-9dec-904eadd65321.png)

Please Review and help!

**Comment by jns4u** [comment]
Just want to help community by answering this specific error fix. It was .properties file update for that respective parameter key name. Although I am getting couple of other java.lang.RuntimeException that will try to resolve and ask for resolution in separate threads.

**Comment by jns4u** [comment]
Above issue was resolved now getting following issue 
![image](https://user-images.githubusercontent.com/14173650/67456184-83766580-f64d-11e9-9c9a-e50265fa3de7.png)
Please help resolving this case!

**Comment by jns4u** [comment]
I resolved this issue by setting correct aws service permission for my account and using key/secret with those permission for client consumer application.
