### ISSUE TITLE
[Question] Strange class file /unison/com/e007... LeaseTaker

### ISSUE THREAD

**Issue by suztomo** [awslabs/amazon-kinesis-client#654]
My static analysis tool found amazon-kinesis-client-1.13.0.jar contains a strange class file at `/unison/com/e007f77498fd27177e2ea931a06dcf50/unison/tmp/amazonaws/services/kinesis/leases/impl/LeaseTaker.class`.

Would you explain why the class file has such a strange path?

```
Exception in thread "main" java.io.IOException: Corrupt jar file /usr/local/google/home/suztomo/.m2/repository/com/amazonaws/amazon-kinesis-client/1.13.0/amazon-kinesis-client-1.13.0.jar; could not load .unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp.amazonaws.services.kinesis.leases.impl.LeaseTaker
        at com.google.cloud.tools.opensource.classpath.ClassDumper.listClasses(ClassDumper.java:393)
        at com.google.cloud.tools.opensource.classpath.ClassDumper.findSymbolReferences(ClassDumper.java:153)
        at com.google.cloud.tools.opensource.classpath.LinkageChecker.create(LinkageChecker.java:78)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:49)
Caused by: java.lang.ClassNotFoundException: Exception while looking for class .unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp.amazonaws.services.kinesis.leases.impl.LeaseTaker: java.io.IOException: Couldn't find: /unison/com/e007f77498fd27177e2ea931a06dcf50/unison/tmp/amazonaws/services/kinesis/leases/impl/LeaseTaker.class
        at org.apache.bcel.util.AbstractClassPathRepository.loadClass(AbstractClassPathRepository.java:77)
        at org.apache.bcel.util.ClassPathRepository.loadClass(ClassPathRepository.java:31)
        at com.google.cloud.tools.opensource.classpath.FixedSizeClassPathRepository.loadClass(FixedSizeClassPathRepository.java:108)
        at com.google.cloud.tools.opensource.classpath.ClassDumper.listClasses(ClassDumper.java:389)
        ... 3 more
Caused by: java.io.IOException: Couldn't find: /unison/com/e007f77498fd27177e2ea931a06dcf50/unison/tmp/amazonaws/services/kinesis/leases/impl/LeaseTaker.class
        at org.apache.bcel.util.ClassPath.getClassFile(ClassPath.java:666)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckClassPath.getInputStream(LinkageCheckClassPath.java:72)
        at org.apache.bcel.util.ClassPath.getInputStream(ClassPath.java:688)
        at org.apache.bcel.util.AbstractClassPathRepository.loadClass(AbstractClassPathRepository.java:75)

```

**Comment by Cory-Bradshaw** [comment]
Thanks for reporting this. We are working on another release to address some backward compatible problems with the recent release and that should address this as well. This file is a lock file for unison, which shouldn't be included in the release.

Sorry for the confusion.

**Comment by suztomo** [comment]
@Cory-Bradshaw Thank you for response.
