### ISSUE TITLE
Unexpected exception was thrown - java.lang.InterruptedException

### ISSUE THREAD

**Issue by dwikle** [awslabs/amazon-kinesis-client#661]
I'm occasionally getting this unexpected error from the Kinesis Consumer Library.

## Error
```
shardId-000000003303 :  Unexpected exception was thrown. This could probably be an issue or a bug. Please search for the exception/error online to check what is going on. If the issue persists or is a recurring problem, feel free to open an issue on, https://github.com/awslabs/amazon-kinesis-client.
```

I couldn't find much online and AWS support was not able to point to a root cause.

## Stack Trace
```
java.lang.RuntimeException: java.lang.InterruptedException
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:279)
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:111)
	at software.amazon.kinesis.retrieval.polling.SynchronousGetRecordsRetrievalStrategy.getRecords(SynchronousGetRecordsRetrievalStrategy.java:34)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.makeRetrievalAttempt(PrefetchRecordsPublisher.java:422)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.run(PrefetchRecordsPublisher.java:405)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at software.amazon.kinesis.common.FutureUtils.resolveOrCancelFuture(FutureUtils.java:28)
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:270)
	... 7 common frames omitted
```

## Configuration
Running the KCL, version 2.2.6
*Not* running enhanced fan-out

When we see this in the logs it's usually happens for multiple shards at around the same time. 

Are there more details I can provide to help find the root cause of this issue?

**Comment by dwikle** [comment]
I have upgraded to version `2.2.7` of the KCL and continue to see these errors.  Is there anything I can do to help diagnose the underlying issue?  Or help move this along in some way?

The feedback from AWS support was along the lines of _the errors don't indicate problems with performance or processing, so it's not a high priority_.

I'd like to avoid having unactionable ERRORs in our applications logs - would a reasonable approach here be to change the logging level to WARN?

**Comment by dbottini2** [comment]
I have also been experiencing this issue on a regular basis, and would also like to avoid having unactionable ERRORs in the logs.

```message: shardId-000000000033 :  Unexpected exception was thrown. This could probably be an issue or a bug. Please search for the exception/error online to check what is going on. If the issue persists or is a recurring problem, feel free to open an issue on, https://github.com/awslabs/amazon-kinesis-client.
   stack_trace: java.lang.RuntimeException: java.lang.InterruptedException
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:279)
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:111)
	at software.amazon.kinesis.retrieval.polling.SynchronousGetRecordsRetrievalStrategy.getRecords(SynchronousGetRecordsRetrievalStrategy.java:34)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.makeRetrievalAttempt(PrefetchRecordsPublisher.java:422)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.run(PrefetchRecordsPublisher.java:405)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at software.amazon.kinesis.common.FutureUtils.resolveOrCancelFuture(FutureUtils.java:28)
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:270)
	... 7 common frames omitted```

**Comment by praetp** [comment]
I saw this as well when running 2.2.9 consumer.

**Comment by tbalthazard** [comment]
2020-11-04 Same problem 
`
11:21:49.951 RequestId=- prefetch-cache-shardId-000000000042-0000 ERROR s.a.k.r.p.PrefetchRecordsPublisher - prod-events:shardId-000000000042 : Unexpected exception was thrown. This could probably be an issue or a bug. Please search for the exception/error online to check what is going on. If the issue persists or is a recurring problem, feel free to open an issue on, https://github.com/awslabs/amazon-kinesis-client.
java.lang.RuntimeException: java.lang.InterruptedException
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:336) ~[amazon-kinesis-client-2.3.1.jar!/:na]
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:135) ~[amazon-kinesis-client-2.3.1.jar!/:na]
	at software.amazon.kinesis.retrieval.polling.SynchronousGetRecordsRetrievalStrategy.getRecords(SynchronousGetRecordsRetrievalStrategy.java:36) ~[amazon-kinesis-client-2.3.1.jar!/:na]
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.makeRetrievalAttempt(PrefetchRecordsPublisher.java:429) [amazon-kinesis-client-2.3.1.jar!/:na]
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.run(PrefetchRecordsPublisher.java:412) [amazon-kinesis-client-2.3.1.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347) ~[na:1.8.0_212]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_212]
	at software.amazon.kinesis.common.FutureUtils.resolveOrCancelFuture(FutureUtils.java:28) ~[amazon-kinesis-client-2.3.1.jar!/:na]
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getGetRecordsResponse(KinesisDataFetcher.java:294) ~[amazon-kinesis-client-2.3.1.jar!/:na]
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:328) ~[amazon-kinesis-client-2.3.1.jar!/:na]
	... 7 common frames omitted
`

**Comment by dmitryyolkin** [comment]
Same problem today on one shard DataStream. KCL v. 2.3.1
```
14-11-2020 18:13:39.469 [prefetch-cache-shardId-000000000000-0000] ERROR s.a.k.r.p.PrefetchRecordsPublisher.makeRetrievalAttempt - 118327460186:MVPAPI02-GPSDataStream-3FB225UY9JX7:1:shardId-000000000000 :  Unexpected exception was thrown. This could probably be an issue or a bug. Please search for the exception/error online to check what is going on. If the issue persists or is a recurring problem, feel free to open an issue on, https://github.com/awslabs/amazon-kinesis-client.
java.lang.RuntimeException: java.lang.InterruptedException
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:336)
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:135)
	at software.amazon.kinesis.retrieval.polling.SynchronousGetRecordsRetrievalStrategy.getRecords(SynchronousGetRecordsRetrievalStrategy.java:36)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.makeRetrievalAttempt(PrefetchRecordsPublisher.java:429)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.run(PrefetchRecordsPublisher.java:412)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at software.amazon.kinesis.common.FutureUtils.resolveOrCancelFuture(FutureUtils.java:28)
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getGetRecordsResponse(KinesisDataFetcher.java:294)
	at software.amazon.kinesis.retrieval.polling.KinesisDataFetcher.getRecords(KinesisDataFetcher.java:328)
	... 7 common frames omitted
```

**Comment by emosqueda** [comment]
I am having the same issue when running 2.3.1 consumer...

Did you find any way to avoid this? @dmitryyolkin

**Comment by tbalthazard** [comment]
@emosqueda and @dmitryyolkin When I got this stack trace, my issue was not linked to kinesis.
In fact it was a memory problem, too much data loaded in memory by CRON jobs. But kinesis just keeping flooded the log hidding the real causes, It loses connection (in my case surely due to my memory problem) then try to reconnect in loop.
I stopped every jobs and kinesis did run well then I started jobs one by one to find out which one cause the issue, hopes it will help you

**Comment by goldmar** [comment]
Hi, is there any progress on this ticket? I've been getting a lot of these errors in my application and started to look into the source code. I find it somewhat strange. Referring to the stacktrace above (it looks the same in my case):

- `Future::get` throws an `InterruptedException` if the current thread was interrupted while waiting
- `FutureUtils::resolveOrCancelFuture` propagates it up
- `KinesisDataFetcher:: getGetRecordsResponse` propagates it up
- `KinesisDataFetcher::getRecords` catches it, emits some debug logging, wraps it in a `RuntimeException`, and throws that
- `SynchronousGetRecordsRetrievalStrategy::getRecords` propagates the `RuntimeException` up
- `PrefetchRecordsPublisher::makeRetrievalAttempt `has a clause to catch an InterruptedException and log it on info level, however we are dealing with a `RuntimeException` at this point; it is not handled and propagated up
- `PrefetchRecordsPublisher::run` catches all `Throwable`s and emits "unexpected exception" on error level.

Is there any reason why the `InterruptedException` is wrapped in a `RuntimeException`? Is this condition actually unexpected and should it be logged on error level?

**Comment by goldmar** [comment]
In my case the issue was that the default setting of `failoverTimeMillis`, which is 10 seconds, was too low for my application. The debug logs showed that the workers were constantly losing their leases and shutting down. Increasing `failoverTimeMillis` apparently fixed the issue.

It seems that this exception is currently always surfacing when a lease is lost. The problem seems to be that the exception is wrapped in a `RuntimeException` as described above; if that did not happen, this would not emit an error log.

**Comment by rtyley** [comment]
> In my case the issue was that the default setting of `failoverTimeMillis`, which is 10 seconds, was too low for my application.

This was a good fix for us. We had two applications reading a Kinesis Stream of 44 shards, one application had 6 `t4g.medium` EC2 instances reading the stream, the other application was just using 1 `t4g.medium` instance. Although the second application was capable of processing the stream in general, it had many `java.lang.InterruptedException`s occurring at startup, presumably because it couldn't renew all 44 leases in time.

We did a few deploys with `failoverTimeMillis` set to different values:

| `failoverTimeMillis` | Deploy 1 (errors) | Deploy 2 (errors) | Deploy 3 (errors) |
|----------------------|-------------------|-------------------|-------------------|
| 10000                | 49                | 25                | N/A               |
| 20000                | 0                 | 18                | 0                 |
| 30000                | 1                 | 0                 | 16                |
| 60000                | 1                 | 0                 | 4                |
| 120000                | 0                 | 0                 | 0                |

You can see that in our case, a `failoverTimeMillis` of 120000ms (2 minutes) was enough to get rid of the noisy `InterruptedException`s.

**Comment by vvo** [comment]
@matrix33 You can update that in the "properties" file here: https://github.com/awslabs/amazon-kinesis-client-nodejs/blob/master/samples/click_stream_sample/consumer/sample.properties
