### ISSUE TITLE
Kinesis shard processors hung on shutdown with large shard count and cleanupLeasesUponShardCompletion disabled

### ISSUE THREAD

**Issue by sbabu-salesforce** [awslabs/amazon-kinesis-client#675]
Hello, 

We've encountered an interesting issue with kinesis processing of child shards on rollovers from terminates getting delayed by over an hour from shutdown calls hanging on the parent shard. Grabbing a thread dump of the server during this issue shows a relatively glaring issue boiling down: 
- to initializing and shutting down record processors of terminated shards (with checkpoint `SHARD_END`) on KCL server startup
- running a `describeStream` call to AWS in the `ShutdownTask` inside a synchronized block
- AWS enforcing 10 describeStream calls per second per account

What we end up with is a single thread trying to run describeStream against AWS, and retrying on any throttling, while all other threads are waiting for the lock to do the same. On a stream with ~240 active shards, and ~2100 total shards (most checkpointed to `SHARD_END` because `cleanupLeasesUponShardCompletion` is disabled in our KCL configuration), we noticed over 200 threads hung in this trace: 

```
"stream-processor-0048" #114 prio=5 os_prio=0 cpu=82.97ms elapsed=109.06s allocated=6127K defined_classes=0 tid=0x00007f8ffc951000 nid=0xc5 waiting for monitor entry  [0x00007f8f450ce000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy.getShardList(DynamoDBStreamsProxy.java:212)
	- waiting to lock <0x0000000561a4ad28> (a com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask.call(ShutdownTask.java:110)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)
   Locked ownable synchronizers:
	- <0x0000000562c6e070> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

and a single thread holding the object lock running the describe streams (with retry pauses):

```
"stream-processor-1038" #1160 prio=5 os_prio=0 cpu=6.59ms elapsed=89.19s allocated=1308K defined_classes=0 tid=0x00007f8ffcdf7800 nid=0x4ee sleeping [0x00007f8f02cbc000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@11.0.2/Native Method)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doPauseBeforeRetry(AmazonHttpClient.java:1781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.pauseBeforeRetry(AmazonHttpClient.java:1755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1264)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.doInvoke(AmazonDynamoDBStreamsClient.java:686)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.invoke(AmazonDynamoDBStreamsClient.java:653)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.invoke(AmazonDynamoDBStreamsClient.java:642)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.executeDescribeStream(AmazonDynamoDBStreamsClient.java:361)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.describeStream(AmazonDynamoDBStreamsClient.java:332)
	at com.salesforce.dynamodbv2.mt.mappers.DelegatingAmazonDynamoDbStreams.describeStream(DelegatingAmazonDynamoDbStreams.java:41)
	at com.salesforce.dynamodbv2.mt.util.CachingAmazonDynamoDbStreams.loadStreamDescriptionForAllShards(CachingAmazonDynamoDbStreams.java:735)
	at com.salesforce.dynamodbv2.mt.util.CachingAmazonDynamoDbStreams.describeStream(CachingAmazonDynamoDbStreams.java:774)
	at com.salesforce.dynamodbv2.mt.mappers.MtAmazonDynamoDbStreamsBase.describeStream(MtAmazonDynamoDbStreamsBase.java:109)
	at com.amazonaws.services.dynamodbv2.streamsadapter.AmazonDynamoDBStreamsAdapterClient.describeStream(AmazonDynamoDBStreamsAdapterClient.java:250)
	at com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy.getStreamInfo(DynamoDBStreamsProxy.java:165)
	at com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy.buildShardGraphSnapshot(DynamoDBStreamsProxy.java:266)
	at com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy.getShardList(DynamoDBStreamsProxy.java:220)
	- locked <0x0000000561a4ad28> (a com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask.call(ShutdownTask.java:110)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)
```

As a consequence, we see times reported to CloudWatch of min/avg/max shutdown times of shard processors all above an hour on unlucky restarts of our KCL processors, so we see regular spikes of 1-2+ hour latencies of records showing up to our stream processors following a shard rollover, with a child waiting on the order of hours to start processing, once the parent finally finishes shutting down. 

Our theory is, the high shard count we're running with on this environment coupled with `cleanupLeasesUponShardCompletion` disabled on our KCL processors, is triggering this, because we have a thundering heard of shard processors trying to run a `ShutdownTask`, and colliding on a synchronized block running code being throttled and retried against AWS (describeStream) on routine restarts of KCL processor JVM's. One potential simple fix would be to just not initialize and shutdown shards checkpointed to `SHARD_END` on the lease table, but I don't have enough experience working with/in KCL to make such a change.

**Comment by MihirLimbachia** [comment]
Hi,
You may use periodic shard sync strategy instead. It ensures that the DescribeStream API call is made every second.

https://github.com/awslabs/amazon-kinesis-client/blob/v1.x/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/PeriodicShardSyncStrategy.java

https://github.com/awslabs/amazon-kinesis-client/blob/02c2036d5dc822efc818cb6f51b6dd0393e4b3ca/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/PeriodicShardSyncManager.java#L37

Morover, by default, one leader worker will be elected using DeterministicShuffleShardSyncLeaderDecider who will take care of updating the leases in the DDB table after making the DescribeStream API call.

https://github.com/awslabs/amazon-kinesis-client/blob/02c2036d5dc822efc818cb6f51b6dd0393e4b3ca/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/DeterministicShuffleShardSyncLeaderDecider.java#L72

https://github.com/awslabs/amazon-kinesis-client/blob/02c2036d5dc822efc818cb6f51b6dd0393e4b3ca/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L1388

Please note that the PeriodicShardSyncStrategy does not do DescribeStream API calls in shutDownTask and would not cause it to hang due to throttling on DescribeStream. One leader worker will take care of updating the leases.

**Comment by sbabu-salesforce** [comment]
Hi Mihir, 

Thanks for your reply. I tried out your suggestion, and I'm afraid there's one invalid assumption in switching shard sync strategies. This statement doesn't seem to hold up:

> Please note that the PeriodicShardSyncStrategy does not do DescribeStream API calls in shutDownTask and would not cause it to hang due to throttling on DescribeStream. One leader worker will take care of updating the leases.

Looking at ShutdownTask, there is no check for the shard sync strategy before running a describe streams call, so actually switching to PeriodicShardSyncStrategy makes the problem worse, of having a background thread calling describeStream, in addition to all the shards shutting down, adding to the throttling. 

https://github.com/awslabs/amazon-kinesis-client/blob/v1.x/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/ShutdownTask.java#L110

After switching to periodic shard strategy, rebooting our stream processor on the env that's still hitting this, I still see hundreds of threads waiting for the `DynamoDBStreamsProxy` object mutex:

```
"stream-processor-0920" #1067 prio=5 os_prio=0 cpu=0.69ms elapsed=159.39s tid=0x00007fd4c46ba000 nid=0x4b6 waiting for monitor entry  [0x00007fd48e5a6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy.getShardList(DynamoDBStreamsProxy.java:212)
	- waiting to lock <0x00000007781ef260> (a com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask.call(ShutdownTask.java:110)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
```

**Comment by lehien** [comment]
Hi @sbabu-salesforce 
Sorry for not answering your question but how do you shutdown your kinesis consumer?
I am developing a kinesis consumer to process logs from Kinesis, but I plan to run it as a crontab, it means the consumer will run every minute or 5 minutes, etc. After getting and consuming a specific number of records, I want to stop it but it seemed not worked at all with graceful shutdown.
Thank you.

**Comment by MihirLimbachia** [comment]
> Hi Mihir,
> 
> Thanks for your reply. I tried out your suggestion, and I'm afraid there's one invalid assumption in switching shard sync strategies. This statement doesn't seem to hold up:
> 
> > Please note that the PeriodicShardSyncStrategy does not do DescribeStream API calls in shutDownTask and would not cause it to hang due to throttling on DescribeStream. One leader worker will take care of updating the leases.
> 
> Looking at ShutdownTask, there is no check for the shard sync strategy before running a describe streams call, so actually switching to PeriodicShardSyncStrategy makes the problem worse, of having a background thread calling describeStream, in addition to all the shards shutting down, adding to the throttling.
> 
> https://github.com/awslabs/amazon-kinesis-client/blob/v1.x/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/ShutdownTask.java#L110
> 
> After switching to periodic shard strategy, rebooting our stream processor on the env that's still hitting this, I still see hundreds of threads waiting for the `DynamoDBStreamsProxy` object mutex:
> 
> ```
> "stream-processor-0920" #1067 prio=5 os_prio=0 cpu=0.69ms elapsed=159.39s tid=0x00007fd4c46ba000 nid=0x4b6 waiting for monitor entry  [0x00007fd48e5a6000]
>    java.lang.Thread.State: BLOCKED (on object monitor)
> 	at com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy.getShardList(DynamoDBStreamsProxy.java:212)
> 	- waiting to lock <0x00000007781ef260> (a com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy)
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask.call(ShutdownTask.java:110)
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
> 	at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
> ```

you are correct, the logic should change based on shard sync strategy.

Basically we do not need latest shards unless we are using it for ShardEndSyncStrategy.

Hence, the KCL developers should change it.
