### ISSUE TITLE
Running with logging set to DEBUG reveals format exception

### ISSUE THREAD

**Issue by Paul424** [awslabs/amazon-kinesis-client#68]
When running an application using Kinesis Connectors Library 1.6.2 i encountered a string format exception.

Relevant part of the callstack:

2016-05-12 11:14:48,123 @LeaseCoordinator-1 ERROR LeaseCoordinator Throwable encountered in lease taking thread LeaseCoordinator.java(167)
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.amazonaws.services.kinesis.leases.impl.LeaseTaker.chooseLeasesToSteal(LeaseTaker.java:471)
	at com.amazonaws.services.kinesis.leases.impl.LeaseTaker.computeLeasesToTake(LeaseTaker.java:391)
	at com.amazonaws.services.kinesis.leases.impl.LeaseTaker.takeLeases(LeaseTaker.java:169)
	at com.amazonaws.services.kinesis.leases.impl.LeaseTaker.takeLeases(LeaseTaker.java:118)
	at com.amazonaws.services.kinesis.leases.impl.LeaseCoordinator.runTaker(LeaseCoordinator.java:219)
	at com.amazonaws.services.kinesis.leases.impl.LeaseCoordinator$TakerRunnable.run(LeaseCoordinator.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by manango** [comment]
@Paul424, thanks for reporting the issue. [Release 1.6.3](https://github.com/awslabs/amazon-kinesis-client/releases/tag/v1.6.3) has the fix for this issue.
