### ISSUE TITLE
Stream deletion causes ShardConsumer to continually attempt shutdown

### ISSUE THREAD

**Issue by mwm-twx** [awslabs/amazon-kinesis-client#69]
Deleting a stream while a worker is still running causes the ShardConsumer to continually attempt execution of the ShutdownTask.  Since the ShutdownReason is TERMINATE, the shutdown task attempts to find child shards; failing with a ResourceNotFoundException.

Steps to reproduce:
1. Create new kinesis stream
1. Start a worker, which creates an IRecordProcessor
1. Delete the kinesis stream

Expected result:
1. IRecordProcessor is shutdown and Worker thread ends

Actual result:
1. IRecordProcessor repeatedly receives the shutdown callback (every second).  Log shows the following exception:
```
ERROR c.a.s.k.c.lib.worker.ShutdownTask - Caught exception: 
com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream STREAM_NAME under account ACCOUNT_ID not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: SOME_UUID)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389) ~[aws-java-sdk-core-1.10.67.jar:na]
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902) ~[aws-java-sdk-core-1.10.67.jar:na]
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) ~[aws-java-sdk-core-1.10.67.jar:na]
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) ~[aws-java-sdk-core-1.10.67.jar:na]
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) ~[aws-java-sdk-core-1.10.67.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) ~[aws-java-sdk-core-1.10.67.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:1769) ~[aws-java-sdk-kinesis-1.10.67.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:649) ~[aws-java-sdk-kinesis-1.10.67.jar:na]
	at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getStreamInfo(KinesisProxy.java:169) ~[amazon-kinesis-client-1.6.2.jar:na]
	at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getShardList(KinesisProxy.java:223) ~[amazon-kinesis-client-1.6.2.jar:na]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.getShardList(ShardSyncer.java:288) ~[amazon-kinesis-client-1.6.2.jar:na]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:112) ~[amazon-kinesis-client-1.6.2.jar:na]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:88) ~[amazon-kilient-1.6.2.jar:na]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask.call(ShutdownTask.java:122) ~[amazon-kinesis-client-1.6.2.jar:na]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [amazon-kinesis-client-1.6.2.jar:na]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24) [amazon-kinesis-client-1.6.2.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
```

**Comment by pfifer** [comment]
Thanks for this report.  

We're tracking the bug, and will prioritize fixing it accordingly.  If this is affecting anyone else please comment, or provide a reaction to the comment to assist us in prioritizing the fix.
