### ISSUE TITLE
Encounter NoSuchMethodException while setting metricsEnabledDimensions in properties file

### ISSUE THREAD

**Issue by starrlingo** [awslabs/amazon-kinesis-client#692]
I'm trying to set the metricsEnabledDimensions in .properties file as follows.
`
metricsEnabledDimensions = Operation, ShardId
`

However, the KCL consumer application throws NoSuchMethodException:

`2020-02-21 07:46:42,225 [main] WARN  s.a.k.multilang.config.RetrievalMode [NONE] - Some polling properties have been set, defaulting to polling. To switch to Fanout either add `RetrievalMode=FANOUT` to your properties or remove the any configuration for polling.
java.lang.RuntimeException: java.lang.NoSuchMethodException: software.amazon.kinesis.metrics.MetricsConfig.metricsEnabledDimensions(java.util.HashSet)
	at software.amazon.kinesis.multilang.config.ConfigurationSettableUtils.resolveFields(ConfigurationSettableUtils.java:96)
	at software.amazon.kinesis.multilang.config.MultiLangDaemonConfiguration.resolveFields(MultiLangDaemonConfiguration.java:315)
	at software.amazon.kinesis.multilang.config.MultiLangDaemonConfiguration.resolvedConfiguration(MultiLangDaemonConfiguration.java:384)
	at software.amazon.kinesis.multilang.config.MultiLangDaemonConfiguration.build(MultiLangDaemonConfiguration.java:391)
	at software.amazon.kinesis.multilang.MultiLangDaemon.buildScheduler(MultiLangDaemon.java:120)
	at software.amazon.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:222)
Caused by: java.lang.NoSuchMethodException: software.amazon.kinesis.metrics.MetricsConfig.metricsEnabledDimensions(java.util.HashSet)
	at java.lang.Class.getMethod(Class.java:1786)
	at software.amazon.kinesis.multilang.config.ConfigurationSettableUtils.resolveFields(ConfigurationSettableUtils.java:94)
	... 5 more
java.lang.NoSuchMethodException: software.amazon.kinesis.metrics.MetricsConfig.metricsEnabledDimensions(java.util.HashSet)`

My KCL version is 2.1.2.

**Comment by EricVentor** [comment]
+1
