### ISSUE TITLE
regular expirediteratorexceptions 

### ISSUE THREAD

**Issue by steve-unitq** [awslabs/amazon-kinesis-client#701]
We are regularly seeing these two errors reported in the logs using the python pip package "amazon-kclpy==2.0.1". 

As far as I have been able to tell there is no rhyme or reason as to when these errors happen. It seems like things recover but as part of our monitoring, I'm trying to investigate what can be done to get rid of these and get confirmation that they are benign?

Our processing logic is fairly naive, I do not think we're doing anything more complicated than the logic in this example: https://docs.aws.amazon.com/streams/latest/dev/kcl2-standard-consumer-python-example.html

```
software.amazon.awssdk.services.kinesis.model.ExpiredIteratorException: Iterator expired. The iterator was created at time Wed Mar 04 01:02:40 UTC 2020 while right now it is Wed Mar 04 01:10:30 UTC 2020 which is further in the future than the tolerated delay of 300000 milliseconds. (Service: Kinesis, Status Code: 400, Request ID: cf2e52e7-6f8a-8ccc-99f7-50a1a83381f5) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.services.kinesis.model.ExpiredIteratorException$BuilderImpl.build(ExpiredIteratorException.java:117) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.services.kinesis.model.ExpiredIteratorException$BuilderImpl.build(ExpiredIteratorException.java:77) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.unmarshall(AwsJsonProtocolErrorUnmarshaller.java:86) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:62) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:41) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.core.internal.http.async.SyncResponseHandlerAdapter.lambda$prepare$0(SyncResponseHandlerAdapter.java:85) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.core.internal.http.async.SyncResponseHandlerAdapter$BaosSubscriber.onComplete(SyncResponseHandlerAdapter.java:127) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:164) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$700(ResponseHandler.java:64) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:274) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.HandlerPublisher.complete(HandlerPublisher.java:408) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.HandlerPublisher.handlerRemoved(HandlerPublisher.java:395) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:670) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:505) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:451) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.http.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:328) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.http.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:189) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:165) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.http.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:148) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.onDataRead(Http2ToHttpInboundAdapter.java:75) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:51) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:42) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodec$DefaultHttp2StreamChannel$Http2ChannelUnsafe.doRead0(ForkedHttp2MultiplexCodec.java:972) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodec$DefaultHttp2StreamChannel$Http2ChannelUnsafe.beginRead(ForkedHttp2MultiplexCodec.java:941) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1386) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:95) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:95) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.HandlerPublisher.requestDemand(HandlerPublisher.java:86) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.http.HttpStreamsHandler$1.requestDemand(HttpStreamsHandler.java:157) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.HandlerPublisher.channelReadComplete(HandlerPublisher.java:384) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:373) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.http.HttpStreamsHandler.channelReadComplete(HttpStreamsHandler.java:214) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.http.HttpStreamsClientHandler.channelReadComplete(HttpStreamsClientHandler.java:30) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:373) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelReadComplete(ChannelInboundHandlerAdapter.java:97) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:373) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.handler.timeout.IdleStateHandler.channelReadComplete(IdleStateHandler.java:295) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:373) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1439) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:971) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodec$DefaultHttp2StreamChannel$Http2ChannelUnsafe.beginRead(ForkedHttp2MultiplexCodec.java:954) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1386) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:95) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:95) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.HandlerPublisher.requestDemand(HandlerPublisher.java:86) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.http.HttpStreamsHandler$1.requestDemand(HttpStreamsHandler.java:157) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:271) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:452) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) 
Mar 03 17:10:30 classificationservice qa-monitor[classificationservice-d4bf7d548-5jxzq]: 	at java.lang.Thread.run(Thread.java:748) 
```

```
Feb 28 15:33:12 normalizationservice qa-monitor[normalizationservice-6997b7dbff-gswqn]: 2020-02-28 23:33:12,365 [aws-java-sdk-NettyEventLoop-1-5] WARN  i.n.h.codec.http2.Http2FrameCodec [NONE] - Stream exception thrown for unkown stream 459609.  
Feb 28 15:33:12 normalizationservice qa-monitor[normalizationservice-6997b7dbff-gswqn]: io.netty.handler.codec.http2.Http2Exception$StreamException: Cannot create stream 459609 greater than Last-Stream-ID 459607 from GOAWAY.
```

**Comment by Cory-Bradshaw** [comment]
Note: amazon-kclpy is not supported or vended by the AWS Kinesis Team, or Amazon in general. It is a customer's custom fork of the KCL for python here: https://github.com/empiricalresults/kclpy. The AWS Kinesis supported library is here: https://github.com/awslabs/amazon-kinesis-client-python

That said,

Iterators, once created are expecting to be used within approximately 5 minutes. If you attempt to use the iterator after not using it for more than 5 minutes, you will see this error.

That said, this could happen more regularly if your processing of each record batch takes longer than expected, or you are on a t-style instance consuming all the CPU capacity not allowing KCL background tasks to complete as expected.

If the behavior is not your concern, and you want to ignore these error messages or attempt to filter them out, since they are fairly innocuous by themselves, though they may point to other problems as referenced above,  you can.

**Comment by revanth1528** [comment]
I'm using java client version 2.2.9 and still facing this issue 

```
software.amazon.awssdk.services.kinesis.model.ExpiredIteratorException: Iterator expired. The iterator was created at time Thu Apr 09 09:39:56 UTC 2020 while right now it is Thu Apr 09 09:45:20 UTC 2020 which is further in the future than the tolerated delay of 300000 milliseconds. (Service: Kinesis, Status Code: 400, Request ID: d4abc25a-7f78-bc74-83a3-32aa8f82f8d1)
```

**Comment by Cory-Bradshaw** [comment]
Please see this document for trouble shooting expired iterators. https://docs.aws.amazon.com/streams/latest/dev/troubleshooting-consumers.html#shard-iterator-expires-unexpectedly

The most likely cause is due to DDB IOPs being under-provisioned.

**Comment by revanth1528** [comment]
Thank you @Cory-Bradshaw , this issue is resolved but facing another issue that processRecords Returns Empty Records Array Even When There is Data in the Stream continuously.For instance, yesterday the consumers are continuously fetching 0 records for more than 6 hours and after restating , it worked fine but the issue is happening frequently now. I have enabled ```callProcessRecordsEvenForEmptyRecordList``` and i've set ```idleMillisBetweenCalls = 5 sec```
I didn't understand what the issue is, please help me out here. 
Thanks again in advance.

**Comment by Cory-Bradshaw** [comment]
@revanth1528 ,

Have you overridden any of the default KCL configurations? One that may be causing problems if if you limit the number of records to return in the get records call, as it can lead to always falling behind when the time to request more records (the 5 seconds delay you're adding in) continually progresses faster than the iterator can.

**Comment by revanth1528** [comment]
@Cory-Bradshaw , thank you for  the quick  response. Below is the configuration for my consumer and please let me know if I'm missing something. And I've over-rid the default ```maxRecords``` value and set it to 5000.

```
 StaticCredentialsProvider staticCredentialsProvider = StaticCredentialsProvider.create( AwsBasicCredentials.create(accessKey, secretKey));
        KinesisAsyncClient kinesisClient = KinesisClientUtil.createKinesisAsyncClient(KinesisAsyncClient.builder().credentialsProvider(staticCredentialsProvider).region(Region.of(region)));
        DynamoDbAsyncClient dynamoClient = DynamoDbAsyncClient.builder().credentialsProvider(staticCredentialsProvider).region(Region.of(region)).build();
        CloudWatchAsyncClient cloudWatchClient = CloudWatchAsyncClient.builder().credentialsProvider(staticCredentialsProvider).region(Region.of(region)).build();
        ConfigsBuilder configsBuilder = new ConfigsBuilder(streamName, applicationName, kinesisClient, dynamoClient, cloudWatchClient,getHostName()+streamName, recordProcessorFactory);
        PollingConfig pollingConfig = new PollingConfig(streamName, kinesisClient);
        pollingConfig.recordsFetcherFactory().idleMillisBetweenCalls(5000L);
        ProcessorConfig processorConfig = configsBuilder.processorConfig();
        processorConfig.callProcessRecordsEvenForEmptyRecordList(true);
        pollingConfig.maxRecords(5000);
        RetrievalConfig retrievalConfig = new RetrievalConfig(kinesisClient, streamName, applicationName).retrievalSpecificConfig(pollingConfig);
        Scheduler scheduler = new Scheduler(
                configsBuilder.checkpointConfig(),
                configsBuilder.coordinatorConfig(),
                configsBuilder.leaseManagementConfig(),
                configsBuilder.lifecycleConfig(),
                configsBuilder.metricsConfig(),
                processorConfig,
                retrievalConfig
        );
        try {
            CompletableFuture.runAsync(scheduler);
        } catch (Throwable t) {
            log.error("Caught throwable while running scheduler for stream data : {} .",streamName, t);
        }
```
And there are multiple consumers consuming from the same stream and the stream is having a single shard. Thanks in advance and extremely sorry for directly tagging you.

**Comment by Cory-Bradshaw** [comment]
@revanth1528 ,

Are you seeing any warnings or errors around throttling? I assume you have set the `idleMillisBetweenCalls` due to having up to 25 consumers on the stream, but that doesn't mean you won't see throttling around throughput if you are pushing through more then 2MB/NumConsumers through the stream.  Also, that 2MB is double the input rate to assist with catch up scenarios, so if your happy-path is consuming the full 2MB out, your consumers would likely be unable to get caught up once they fall behind due to any processing latencies, network problems, etc.

To dig in further I'd need your account ID information, stream name, and region you are using to be able to view what is happening at the stream-level.
