### ISSUE TITLE
Cannot send to kinesis using KinesisAsyncClient

### ISSUE THREAD

**Issue by jlj0n3s** [awslabs/amazon-kinesis-client#711]
`2020-04-13 16:42:55,816 [sdk-ScheduledExecutor-2-1] DEBUG software.amazon.awssdk.request       - Retrying Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=kinesis.us-west-2.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2020-04-13 16:42:58,058 [pool-1-thread-3  ] DEBUG software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain - Creating an interceptor chain that will apply interceptors in the following order: []
2020-04-13 16:42:58,058 [sdk-ScheduledExecutor-2-1] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer - AWS4 String to sign: AWS4-HMAC-SHA256
20200413T234255Z
20200413/us-west-2/kinesis/aws4_request
a959f8b438f30ed11af4062a42308f6c7929ac5bf0e0713d48f7edf7d226686d
2020-04-13 16:42:58,059 [pool-1-thread-3  ] DEBUG software.amazon.awssdk.request       - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=kinesis.us-west-2.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2020-04-13 16:42:58,061 [aws-java-sdk-NettyEventLoop-1-3] WARN  io.netty.channel.ChannelInitializer  - Failed to initialize a channel. Closing: [id: 0xf9fa0881]
java.lang.IllegalStateException: failed to build a Http2ConnectionHandler
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.buildFromCodec(ForkedHttp2MultiplexCodecBuilder.java:189)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.buildFromConnection(ForkedHttp2MultiplexCodecBuilder.java:179)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.build(ForkedHttp2MultiplexCodecBuilder.java:153)
	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.configureHttp2(ChannelPipelineInitializer.java:125)
	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.channelCreated(ChannelPipelineInitializer.java:85)
	at io.netty.channel.pool.SimpleChannelPool$1.initChannel(SimpleChannelPool.java:113)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2FrameCodec.<init>(Lio/netty/handler/codec/http2/Http2ConnectionEncoder;Lio/netty/handler/codec/http2/Http2ConnectionDecoder;Lio/netty/handler/codec/http2/Http2Settings;)V
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodec.<init>(ForkedHttp2MultiplexCodec.java:171)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.build(ForkedHttp2MultiplexCodecBuilder.java:203)
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodecBuilder.buildFromCodec(ForkedHttp2MultiplexCodecBuilder.java:185)
	... 23 common frames omitted
2020-04-13 16:42:58,061 [pool-1-thread-3  ] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer - AWS4 String to sign: AWS4-HMAC-SHA256
20200413T234258Z
20200413/us-west-2/kinesis/aws4_request
7eac13292281b152a4afb40f7b257c87b500783eeb1fbb0714d02a483aeb39ae
`

**Comment by JJonesAtAvaya** [comment]
I am using the latest versions as far as I know.

I even added a dependency on the latest version of Netty in the hopes that might fix it, nope
```

<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>kinesis</artifactId>
            <version>2.11.10</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/software.amazon.kinesis/amazon-kinesis-client -->
        <dependency>
            <groupId>software.amazon.kinesis</groupId>
            <artifactId>amazon-kinesis-client</artifactId>
            <version>2.2.10</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>auth</artifactId>
            <version>2.11.12</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.netty/netty-codec-http2 -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http2</artifactId>
            <version>4.1.48.Final</version>
        </dependency>
```

**Comment by ashwing** [comment]
Hello, can you provide the code snippet of how you building the client?
