### ISSUE TITLE
Kinesis Client Library Checkpoint exceptions

### ISSUE THREAD

**Issue by SuprithaMundaragi** [awslabs/amazon-kinesis-client#732]
We have an implementation of dynamo db streams on a DynamoDB table. But often, especially on node restart, we have the exceptions like this and they do not stop:

`com.amazonaws.services.kinesis.clientlibrary.exceptions.internal.KinesisClientLibIOException: Unable to fetch checkpoint for shardId shardId-00000001596757965421-84b48e8b
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.getCheckpointObject(KinesisClientLibLeaseCoordinator.java:286) ~[amazon-kinesis-client-1.13.3.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask.call(InitializeTask.java:82) [amazon-kinesis-client-1.13.3.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [amazon-kinesis-client-1.13.3.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24) [amazon-kinesis-client-1.13.3.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

It cannot find checkpoints for shards. We have only 1 worker per instance currently and for the stream start position we have `LATEST`. And maybe sometimes instance restart will help, but this defeats the auto scaling policy we have for the micro service. Is there some resolution for this?

**Comment by anekar3416** [comment]
@SuprithaMundaragi Did you find any solution for this?

**Comment by neli-kh** [comment]
Any updates to be had - having same issues on and off between deployments.

**Comment by tinder-raipankaj** [comment]
Hey folks, just checking in—has this issue earned its retirement yet? My KCL is still throwing tantrums (esp. during redeploys) over fetching checkpoints, and it's getting harder to calm it down. Any updates or magic tricks to finally put this one to bed?
