### ISSUE TITLE
Many "GetRecordsResult is not valid" errors for dynamodb streams consumer after 1.14.0 update

### ISSUE THREAD

**Issue by gjesse** [awslabs/amazon-kinesis-client#746]
Hello - yesterday I upgraded to 1.14.0 kcl client for our application that uses dynamodb streams for processing. Since then I've noticed these very consistent errors. we've seen 10s of thousands of these in just a few hours, and repeated for the same shard ids. 

```
ERROR [2020-10-20 17:07:45,185] [RecordProcessor-0015] c.a.s.k.c.lib.worker.ProcessTask: ShardId shardId-00000001603151190143-090943ac: Caught exception: 
com.amazonaws.SdkClientException: Shard shardId-00000001603151190143-090943ac: GetRecordsResult is not valid. NextShardIterator: null. ChildShards: []
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher$AdvancingResult.accept(KinesisDataFetcher.java:126)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.SynchronousGetRecordsRetrievalStrategy.getRecords(SynchronousGetRecordsRetrievalStrategy.java:31)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.BlockingGetRecordsCache.getNextResult(BlockingGetRecordsCache.java:50)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.getRecordsResultAndRecordMillisBehindLatest(ProcessTask.java:377)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.getRecordsResult(ProcessTask.java:342)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:159)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

As best I can tell, a `GetRecordsResult` with a null NextShardIterator and no child shards is a valid response - in fact there is no field specified for child shards at all here:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_GetRecords.html

Using kcl 1.14.0, and creating a worker using dynamodb-streams-kinesis-adapter 1.5.2. The worker is setup using this method: https://github.com/awslabs/dynamodb-streams-kinesis-adapter/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/streamsadapter/StreamsWorkerFactory.java#L44

I am not setting any special configuration other than the following, which I believe shouldn't be relevant.

``` 
 KinesisClientLibConfiguration config =  new KinesisClientLibConfiguration(applicationName,
                                                                                  streamName,
                                                                                  credentialsProvider,
                                                                                  workerId)
                        .withInitialPositionInStream(initialPositionInStream)
                        .withMaxRecords(kclConfiguration.getMaxRecordsToFetch())
                        .withTaskBackoffTimeMillis(kclConfiguration.getBackOffTimeMillis())
                        .withIdleTimeBetweenReadsInMillis(kclConfiguration.getIdleTimeBetweenReads());
```

**Comment by anoopgarlapati** [comment]
I am also facing the same issue in our application.

```
2020-09-30 22:01:19.075 ERROR 1 --- [dProcessor-0000] c.a.s.k.c.l.w.ProcessTask                : ShardId shardId-00000001601475416147-3f4f3663: Caught exception: 

com.amazonaws.SdkClientException: Shard shardId-00000001601475416147-3f4f3663: GetRecordsResult is not valid. NextShardIterator: null. ChildShards: []
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher$AdvancingResult.accept(KinesisDataFetcher.java:126) ~[amazon-kinesis-client-1.14.0.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.SynchronousGetRecordsRetrievalStrategy.getRecords(SynchronousGetRecordsRetrievalStrategy.java:31) ~[amazon-kinesis-client-1.14.0.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.BlockingGetRecordsCache.getNextResult(BlockingGetRecordsCache.java:50) ~[amazon-kinesis-client-1.14.0.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.getRecordsResultAndRecordMillisBehindLatest(ProcessTask.java:377) ~[amazon-kinesis-client-1.14.0.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.getRecordsResult(ProcessTask.java:342) ~[amazon-kinesis-client-1.14.0.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:159) [amazon-kinesis-client-1.14.0.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [amazon-kinesis-client-1.14.0.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24) [amazon-kinesis-client-1.14.0.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
```

I was using amazon-kinesis-client 1.14.0 and dynamodb-streams-kinesis-adapter 1.5.2 and noticed these logs pop up in our staging environment. We currently rolled back this dependency update due to high number of these errors in the logs.

**Comment by ashwing** [comment]
KCK 1.14.0 is not compatible with DDBStreams latest version. Please request
DDBStreams to support their adapter library to work with KCL 1.4.0.

**Comment by ui-mariusz-zawadzki** [comment]
> I am also facing the same issue in our application.
> 
> ```
> 2020-09-30 22:01:19.075 ERROR 1 --- [dProcessor-0000] c.a.s.k.c.l.w.ProcessTask                : ShardId shardId-00000001601475416147-3f4f3663: Caught exception: 
> 
> com.amazonaws.SdkClientException: Shard shardId-00000001601475416147-3f4f3663: GetRecordsResult is not valid. NextShardIterator: null. ChildShards: []
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher$AdvancingResult.accept(KinesisDataFetcher.java:126) ~[amazon-kinesis-client-1.14.0.jar!/:?]
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.SynchronousGetRecordsRetrievalStrategy.getRecords(SynchronousGetRecordsRetrievalStrategy.java:31) ~[amazon-kinesis-client-1.14.0.jar!/:?]
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.BlockingGetRecordsCache.getNextResult(BlockingGetRecordsCache.java:50) ~[amazon-kinesis-client-1.14.0.jar!/:?]
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.getRecordsResultAndRecordMillisBehindLatest(ProcessTask.java:377) ~[amazon-kinesis-client-1.14.0.jar!/:?]
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.getRecordsResult(ProcessTask.java:342) ~[amazon-kinesis-client-1.14.0.jar!/:?]
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:159) [amazon-kinesis-client-1.14.0.jar!/:?]
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [amazon-kinesis-client-1.14.0.jar!/:?]
> 	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24) [amazon-kinesis-client-1.14.0.jar!/:?]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_261]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
> ```
> 
> I was using amazon-kinesis-client 1.14.0 and dynamodb-streams-kinesis-adapter 1.5.2 and noticed these logs pop up in our staging environment. We currently rolled back this dependency update due to high number of these errors in the logs.

Hi. I'm facing identical issues while working on new implemenation to consume dynamodb stream. @anoopgarlapati Would you be so kind and share versions that worked for you?

**Comment by gjesse** [comment]
> versions that worked for you

@ui-mariusz-zawadzki use kcl previous release `1.13.3` and dynamodb-streams-kinesis-adapter `1.5.2`

**Comment by gjesse** [comment]
> KCK 1.14.0 is not compatible with DDBStreams latest version. Please request DDBStreams to support their adapter library to work with KCL 1.4.0.

I've opened a matching issue with that repo: https://github.com/awslabs/dynamodb-streams-kinesis-adapter/issues/40
