### ISSUE TITLE
Kinesis shutdown errors

### ISSUE THREAD

**Issue by afreen-aliya** [awslabs/amazon-kinesis-client#914]
When shutting down kinesis, we get a few shutdown errors. One of them being: 
```
java.lang.IllegalStateException: Shutdown has been called on the cache, can't accept new requests.
    at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.throwOnIllegalState(PrefetchRecordsPublisher.java:283)
    at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.peekNextResult(PrefetchRecordsPublisher.java:292)
    at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.drainQueueForRequests(PrefetchRecordsPublisher.java:388)
    at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.makeRetrievalAttempt(PrefetchRecordsPublisher.java:506)
    at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.run(PrefetchRecordsPublisher.java:464)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

We are aware that [the error is an expected part of the graceful shutdown](https://github.com/awslabs/amazon-kinesis-client/pull/857#issuecomment-946675043) but it creates a lot of noise in our logs and sometimes we get paged as well. Can this issue please be fixed?

**Comment by royyeah** [comment]
We also run into this.

**Comment by weaselmetal** [comment]
Please fix this. Like already said in the OP, an `IllegalStateException` can't be considered the graceful way to shut down.

**Comment by montelius** [comment]
Would also appreciate if this was fixed

**Comment by tzfromaz** [comment]
Bumping this issue.

**Comment by patricm-enbw** [comment]
It looks like nobody cares :(

**Comment by praetp** [comment]
Anyone ?

**Comment by vsadokhin** [comment]
+1 to solve this one 🙏

```
17:41:05.218 [prefetch-cache-shardId-000000000000-0000] ERROR s.a.k.r.p.PrefetchRecordsPublisher - testStream-WselIrnpyM:shardId-000000000000 :  Unexpected exception was thrown. This could probably be an issue or a bug. Please search for the exception/error online to check what is going on. If the issue persists or is a recurring problem, feel free to open an issue on, https://github.com/awslabs/amazon-kinesis-client.
java.lang.IllegalStateException: Shutdown has been called on the cache, can't accept new requests.
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.throwOnIllegalState(PrefetchRecordsPublisher.java:283)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.peekNextResult(PrefetchRecordsPublisher.java:292)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.drainQueueForRequests(PrefetchRecordsPublisher.java:388)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.makeRetrievalAttempt(PrefetchRecordsPublisher.java:506)
	at software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher$DefaultGetRecordsCacheDaemon.run(PrefetchRecordsPublisher.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

How it is designed now is `peekNextResult` private method calls `throwOnIllegalState` before :
```java
    private void throwOnIllegalState() {
        if (executorService.isShutdown()) {
            throw new IllegalStateException("Shutdown has been called on the cache, can't accept new requests.");
        }

        if (!started) {
            throw new IllegalStateException("Cache has not been initialized, make sure to call start.");
        }
    }

    private PrefetchRecordsRetrieved peekNextResult() {
        throwOnIllegalState();
        return publisherSession.peekNextRecord();
    }
```
and if it is a shutdown it will throw `IllegalStateException` that will work internally like breaking and goto operator to `DefaultGetRecordsCacheDaemon.run` `catch (Throwable e)` block that logs this with error level. It is arguable how much it is an error as shutdown is expected to happen on app stop / redeploy etc.  

The solution seems very easy to do and not breaking the rest, instead of doing in `throwOnIllegalState`:
```java
        if (executorService.isShutdown()) {
            throw new IllegalStateException("Shutdown has been called on the cache, can't accept new requests.");
        }
```
just do this in `drainQueueForRequests`:
```java
    synchronized void drainQueueForRequests() {
        if (executorService.isShutdown()) {
            return;
        }
        final PrefetchRecordsRetrieved recordsToDeliver = peekNextResult();
// .. the rest
    }
```
Of course it is up to the team to decide how to exactly deal with it, but the main point is shutdown is not an exceptional but more like expected valid scenario for `PrefetchRecordsPublisher` so there is no need in exception nor log.error.

**Comment by michaelzelaia** [comment]
+1
It's not during a KCL graceful shutdown only; the same can happen when a lease is lost by one of the workers. I've got a multi-threaded client and during the initial lease distribution (normally one thread/worker takes all leases and then they are gradually distributed across the workers) I observe this happening quite often in my tests.

**Comment by imrekoszo** [comment]
We're still seeing this with KCL 2.6.0:

```
...
Caused by: java.lang.NullPointerException Actually not, but can't throw other exceptions due to RS 
    Flowable.java:16022 io.reactivex.rxjava3.core.Flowable.subscribe
    Flowable.java:15959 io.reactivex.rxjava3.core.Flowable.subscribe
    FlowableSubscribeOn.java:82 io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run
    ExecutorScheduler.java:324 io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run
    ExecutorScheduler.java:289 io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager
    ExecutorScheduler.java:250 io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run
    unknown java.util.concurrent.ThreadPoolExecutor.runWorker
    unknown java.util.concurrent.ThreadPoolExecutor$Worker.run
    unknown java.lang.Thread.run

Caused by: java.lang.IllegalStateException Shutdown has been called on the cache, can't accept new requests. 
    PrefetchRecordsPublisher.java:283 software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.throwOnIllegalState
    PrefetchRecordsPublisher.java:338 software.amazon.kinesis.retrieval.polling.PrefetchRecordsPublisher.subscribe
    FlowableFromPublisher.java:29 io.reactivex.rxjava3.internal.operators.flowable.FlowableFromPublisher.subscribeActual
    Flowable.java:16013 io.reactivex.rxjava3.core.Flowable.subscribe
    Flowable.java:15959 io.reactivex.rxjava3.core.Flowable.subscribe
    FlowableSubscribeOn.java:82 io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run
    ExecutorScheduler.java:324 io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run
    ExecutorScheduler.java:289 io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager
    ExecutorScheduler.java:250 io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run
    unknown java.util.concurrent.ThreadPoolExecutor.runWorker
    unknown java.util.concurrent.ThreadPoolExecutor$Worker.run
    unknown java.lang.Thread.run
```
